### PR TITLE
Fix logging level for both root and Bugsnag not being initialized

### LINKED ISSUE #682: Debug message printed after every command
> 21:57:34.445 [Thread-2] DEBUG com.bugsnag.Bugsnag - Closing connection to Bugsnag

Debug should only print if we have toggled debug mode.

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #682 

Due to lazy initialization of Kotlin's objects logging level was not set (default was used).

## Checklist
- [x] release_notes.md updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/Main.kt [hunk 1]
```diff
@@ -39,7 +39,8 @@ class Main : Runnable {
 
     @CommandLine.Option(
         names = ["--debug"],
-        description = ["Enables debug logging"]
+        description = ["Enables debug logging"],
+        defaultValue = "false"
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/Main.kt]: 👍
