### PR TITLE
Fix an incorrect outcome (corner cases)

### LINKED ISSUE #914: Outcome incorrectly set by Flank
**Describe the bug**
> A clear and concise description of what the bug is.

```
[task 2020-07-23T20:29:15.152Z] ┌─────────┬──────────────────────┬──────────────────────────────────────────┐
[task 2020-07-23T20:29:15.153Z] │ OUTCOME │      MATRIX ID       │               TEST DETAILS               │
[task 2020-07-23T20:29:15.153Z] ├─────────┼──────────────────────┼──────────────────────────────────────────┤
[task 2020-07-23T20:29:15.153Z] │  flaky  │ matrix-1vj2pt9wih182 │ 1 test cases failed, 106 passed, 2 flaky │
[task 2020-07-23T20:29:15.153Z] └─────────┴──────────────────────┴──────────────────────────────────────────┘
```

FTL confirmed the matrix outcome is actually failure. Flank reported flaky.

Let's diagram the Flank outcome setting logic with PlantUML in addition to fixing this bug.

**Expected behavior**
> A clear and concise description of what you expected to happen.

I expected the outcome to match the FTL outcome (failure).

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Flank  v20.07.0

**Additional context**
> Add any other context about the problem here.

https://firebase-community.slack.com/archives/C72V6UW8M/p1595539705001900

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #914 

Due to the incorrectly implemented logic regarding the status update, there were cases when flaky tests obscure failed results.
The following must occur:
1. The matrix needs to have both flaky and failed tests (at least one of each)
2. TestExecutions need to be returned in a specific order:
    1. Failed execution must be consumed by flank before flaky one
    2. The following flaky execution must be actually failed but the outcome of all re-runs is success
3. Then flank does what is the following:
    1. The outcome is set to `failure` when failed test/shards/executions are processed
    ```kotlin
   private fun Outcome?.updateOutcome(
       when {
           ...
           else -> this?.summary  // at this point SavedMatrix.outcome == success, flank changes it to failure
           ...
   })
   ```
    2. When flank reaches case where step summary is `failure` but execution is `success` it sets `SavedMatrix` outcome to flaky
    ```kotlin
   updateOutcome(flakyOutcome = it.step.outcome?.summary != this?.summary) // flakyOutcome == true 
    ```
    3. Due to incorrect order in `when` condition `failure` check is never reached 
    ```kotlin
   private fun Outcome?.updateOutcome(
           flakyOutcome: Boolean
       ) {
           outcome = when {
               flakyOutcome -> flaky 
               // flank should escape here with failure status persisted, but since flakyOutcome == true SavedMatrix.outcome is changed to flaky
               outcome == failure || outcome == inconclusive -> return 
               outcome == flaky -> this?.summary?.takeIf { it == failure || it == inconclusive }
               else -> this?.summary
           } ?: outcome
       }
    ```
    
#### Proposed fix
1. Change order in when condition to always check for `failure` first
    ```kotlin
   private fun Outcome?.updateOutcome(
           flakyOutcome: Boolean
       ) {
           outcome = when {
               outcome == failure || outcome == inconclusive -> return // escape when failure/inconclusive outcome is set
               flakyOutcome -> flaky 
               outcome == flaky -> this?.summary?.takeIf { it == failure || it == inconclusive }
               else -> this?.summary
           } ?: outcome
       }
    ```
2. Add unit tests to cover this case.

All tests pass and build finish successfully.
No easy way to verify it without previously prepared data/results

## Checklist

- [x] Documented
- [x] Unit tested
- [x] release_notes.md updated

### CODE REVIEW

File: test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt [hunk 1]
```diff
@@ -199,8 +200,73 @@ class SavedMatrixTest {
...
-        Assert.assertEquals(expectedOutcome, savedMatrix.outcome)
-        Assert.assertEquals(expectedOutcomeDetails, savedMatrix.outcomeDetails)
-        Assert.assertEquals(INVALID, savedMatrix.state)
+        assertEquals(expectedOutcome, savedMatrix.outcome)
+        assertEquals(expectedOutcomeDetails, savedMatrix.outcomeDetails)
+        assertEquals(INVALID, savedMatrix.state)
+    }
+
+    @Test
+    fun `savedMatrix should have failed outcome when at least one test is failed and the last one is flaky`() {
```
Comment (jan-gogo) [inline test_runner/src/test/kotlin/ftl/json/SavedMatrixTest.kt:209]:
```suggestion
    fun `savedMatrix should have failed outcome when at least one test is failed`() {
```
