### PR TITLE
#793 better error message on file not found

### LINKED ISSUE #793: Better error message on file not found
```
$ flank android run --dump-shards
version: local_snapshot
revision: 881344f4a2f72a4ccb0187a269a38fc4a0b0538f

java.nio.file.NoSuchFileException: ./flank.yml
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.newBufferedReader(Files.java:2816)
	at ftl.args.AndroidArgs$Companion.load(AndroidArgs.kt:193)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at ftl.Main$Companion$main$1.invoke(Main.kt:53)
	at ftl.Main$Companion$main$1.invoke(Main.kt:43)
	at ftl.util.Utils.withGlobalExceptionHandling(Utils.kt:132)
	at ftl.Main$Companion.main(Main.kt:49)
	at ftl.Main.main(Main.kt)
```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #793 

## Checklist

- [X] Documented
- [X] Unit tested
- [X] release_notes.md updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/util/FlankException.kt [hunk 1]
```diff
@@ -69,3 +69,12 @@ class FlankCommonException(message: String) : FlankException(message)
...
 class FlankConfigurationException(message: String) : FlankException(message)
+
+/**
+ *  Exception throws when required yaml file not found
+ *
+ *  Exit code: 1
+ *
+ *  @param message [String] message to be printed to [System.err]
+ */
+class FlankNoSuchFileException(message: String) : FlankException(message)
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/util/FlankException.kt:80]: I am not sure about creating additional exception that would handled the same way as other two. Intention behind `FlankCommonException` was to wrap all errors caused by user. But this is just my opinion. :) 
If you decide to refactor this, please take care of `FlankConfiguratinnException`

File: test_runner/src/main/kotlin/ftl/util/Utils.kt [hunk 2]
```diff
@@ -155,6 +155,10 @@ fun withGlobalExceptionHandling(block: () -> Int) {
                 System.err.println(t)
                 exitProcess(1)
             }
+            is FlankNoSuchFileException -> {
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/util/Utils.kt:158]: This block is duplicated with L154, I think we should reuse code and and write multiple types for one branch.
IMO it would be even better to reuse logic for `FlankCommonException` (L135).

File: test_runner/src/main/kotlin/ftl/util/Utils.kt [hunk 3]
```diff
@@ -155,6 +155,10 @@ fun withGlobalExceptionHandling(block: () -> Int) {
...
+                System.err.println(t)
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/util/Utils.kt:159]: I think user is only interested in message. We don't need to expose our classes. We could print just message here. (this is more cosmetically comment :) )

Other think that just came to my mind if we should stop using `System.err` to print messages. I am wondering if we should stick to stdout. Since it is CLI app user would by default redirect stderr somewhere else. Just thinking, what do you think?

**Comment by bootstraponline** [comment]
I built this branch and tested the code, the new error looks great!

**Comment by bootstraponline** [comment]
@adamfilipow92 I'd like to have a best practice of no merge commits in pull requests. 🙂 Please rebase/force push into a linear history.

File: test_runner/src/main/kotlin/ftl/util/FlankException.kt (hunk 1 above)
Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/util/FlankException.kt:80]: On the second thought I think we should use `FlankFatalError` instead. It is used to indicate users mistakes. Also, exit code will be inline with documentation https://github.com/Flank/flank#exit-codes

Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/util/FlankException.kt:80]: I think you have right. I change this exceptions to ` FlankFatalError ` with return code: 2. 
Thanks for review! :)

File: test_runner/src/main/kotlin/ftl/util/Utils.kt (hunk 2 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/util/Utils.kt:158]: Exception type changed to: FlankFatalError.

File: test_runner/src/main/kotlin/ftl/util/Utils.kt (hunk 3 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/util/Utils.kt:159]: For change to stdout I will make other issue.

**Comment by adamfilipow92** [comment]
> @adamfilipow92 I'd like to have a best practice of no merge commits in pull requests. 🙂 Please rebase/force push into a linear history.

All next conflicts will be resolved by rebase and force push. 🙂

**Comment by bootstraponline** [comment]
> #### Conflicting files
> `release_notes.md`
