### PR TITLE
fix: Invoking flank yml on gcloud cli

### LINKED ISSUE #997: error invoking ios flank with gcloud
**Describe the bug**
> A clear and concise description of what the bug is.

I followed the steps laid out in Flank's read me to configure using flank on circleci. The step to deploy to run tests with Firebase Test Lab keeps failing when trying to run tests using `gcloud alpha firebase test ios run flank.ios.yml:gcloud
`. The error I get is ERROR: (gcloud.alpha.firebase.test.ios.run) Invalid value for [version]: 12.0

**To Reproduce**
> Steps to reproduce the behavior:

1. Run 'gcloud alpha firebase test ios run flank.ios.yml:gcloud'
2. See error (gcloud.alpha.firebase.test.ios.run) Invalid value for [version]: 12.0

**Expected behavior**
> A clear and concise description of what you expected to happen.

Tests should be deployed to Firebase Test Lab or an error description that can be better understood

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
> Yes
> Post the output of ` flank --version`.

version: v20.08.1
revision: e9ed26c8f2fdc77fca9f0e436558d89f7f99ef17

**Additional context**
> Add any other context about the problem here.

I have also tried running `flank ios run` and the result I get is `null`. I'm including the yml file parsing that was printed when running the method
```
version: v20.08.1
revision: e9ed26c8f2fdc77fca9f0e436558d89f7f99ef17
IosArgs
    gcloud:
      results-bucket: cloud-test-${GOOGLE_PROJECT_ID}
      results-dir: circleci-${CIRCLE_BUILD_NUM}
      record-video: true
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # iOS gcloud
      test: /Users/distiller/project/fastlane/test_output/build_products.zip
      xctestrun-file: /Users/distiller/project/UITest_iphonesimulator13.4-x86_64.xctestrun
      xcode-version: null
      device:
        - model: iphone8
          version: 12.0
          locale: en
          orientation: portrait
        - model: iphonexr
          version: 13.2
          locale: en
          orientation: portrait
        - model: iphonese
          version: 11.4
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0
    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: gs://tmp_flank/flank/test_app_ios.xml
      smart-flank-disable-upload: false
      test-targets-always-run:
      files-to-download:
      keep-file-path: false
      full-junit-result: false
      # iOS flank
      test-targets:
      disable-sharding: false
      project: turnstyle-8663d
      local-result-dir: results
      run-timeout: -1
      ignore-failed-tests: false
      output-style: multi
RunTests
  Uploading build_products.zip ..
null
```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #997 

- when flank cannot create the bucket, should fast fail
- gcloud cli understand flank yml

## Problem

```

  device:
  - model: iphone8
    version: 12.0
    orientation: portrait
    locale: en_US

```

flank understand ```version``` even if the value is not in quotes but gcloud cli understand value only in quotes. 
We can allow ```doctor``` to add single quotes to the device version.

## Checklist

- [X] Fast fail when cannot create a bucket
- [X] Doctor can fix ```device.version```
- [X] Unit tested

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/doctor/Doctor.kt [hunk 1]
```diff
@@ -61,3 +67,10 @@ private fun preloadConfiguration(data: Path, isAndroid: Boolean) =
     } catch (e: FlankConfigurationError) {
         e.message
     }
+
+private fun JsonNode.validateDevices() = StringBuilder().apply {
+    getDevicesNode()?.getNotValidDevices()?.forEach { device ->
+        if (device.has(VERSION_NODE))
+            appendLine("Warning: Version should be string $GCLOUD_NODE -> $DEVICES_NODE[${device[MODEL_NODE]}] -> $VERSION_NODE[${device[VERSION_NODE]}]")
+    }
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/doctor/Doctor.kt:75]: How about filter and skip `if` ?

```suggestion
getDevicesNode()?.getNotValidDevices()?.filter {device.has(VERSION_NODE)}?.forEach { device ->
            appendLine("Warning: Version should be string $GCLOUD_NODE -> $DEVICES_NODE[${device[MODEL_NODE]}] -> $VERSION_NODE[${device[VERSION_NODE]}]")
    }
```

File: test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+private fun JsonNode.fixDevices() = also {
+    getDevicesNode()?.getNotValidDevices()?.forEach { device ->
+        device.fixDeviceVersion()
+    }
+}
+
+internal fun JsonNode.getDevicesNode() = get(GCLOUD_NODE).get(DEVICES_NODE)
+
+internal fun JsonNode.getNotValidDevices() = filter { it.deviceVersionValid().not() }
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:24]: How about `filterNot {...}` instead. We could get rid of `.not()`

File: test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+private fun Path.loadYml() = yamlMapper.readTree(loadFile(this))
+
+private fun JsonNode.fixDevices() = also {
+    getDevicesNode()?.getNotValidDevices()?.forEach { device ->
+        device.fixDeviceVersion()
+    }
+}
+
+internal fun JsonNode.getDevicesNode() = get(GCLOUD_NODE).get(DEVICES_NODE)
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:22]: I am thinking about changing extension functions to extension properties. As stated 
 in https://kotlinlang.org/docs/reference/coding-conventions.html#functions-vs-properties
rewriting `getDevicesNode()`, `getNotValidDevices()` etc into properties (example) `JsonNode.devicesNode` would result in  
`devicesNode.notValidDevices.filter { ...}`
We are operating on properties anyway so that always returns the same value. It's not crucial for your PR, I'd like to get you opinion @adamfilipow92 @piotradamczyk5

File: test_runner/src/main/kotlin/ftl/doctor/Doctor.kt (hunk 1 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/doctor/Doctor.kt:75]: 👍

File: test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt (hunk 2 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:24]: 👍

**Review by piotradamczyk5 — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt (hunk 3 above)
Comment (jan-gogo) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:22]: As it is a getter, ofc It could be converted to property. But is a cosmetic change.

Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:22]: Thanks, for this topic! 👍  On the first look, it's looking great. It can cache results so we can avoid computation the same things and in cases when we have ```getSomething()``` it fits better in my opinion.

Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:22]: > As it is a getter, ofc It could be converted to property. But it's a cosmetic change.

Never said otherwise

File: test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+private fun Path.loadYml() = yamlMapper.readTree(loadFile(this))
+
+private fun JsonNode.fixDevices() = also {
+    devicesNode.notValidDevices.forEach { device ->
+        device.fixDeviceVersion()
+    }
+}
+
+internal val JsonNode.devicesNode
+    get() = this.get(GCLOUD_NODE).get(DEVICES_NODE)
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/args/yml/YamlDeviceFix.kt:23]:
```suggestion
    get() = get(GCLOUD_NODE).get(DEVICES_NODE)
```

**Review by jan-gogo — COMMENTED** [review]
Good work 👍

**Review by jan-gogo — APPROVED** [review]

**Comment by piotradamczyk5** [comment]
@Mergifyio refresh
