### PR TITLE
fix: NPE on dumpShards

### LINKED ISSUE #1601: NPE on dump shards
**Describe the bug**
> A clear and concise description of what the bug is.

NPE when running --dump-shards in the flank repo.

**To Reproduce**
> Steps to reproduce the behavior:

0. `cd ./test_runner` in the Flank repo
1. Run `flank android run --dump-shards`
2. See error

```
java.lang.NullPointerException: File(this).parent must not be null
	at ftl.run.DumpShardsKt.createDirectories(DumpShards.kt:74)
	at ftl.run.DumpShardsKt.saveShardChunks(DumpShards.kt:67)
	at ftl.run.DumpShardsKt.dumpShards(DumpShards.kt:29)
	at ftl.run.DumpShardsKt$dumpShards$1.invokeSuspend(DumpShards.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:71)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at ftl.Main$Companion$main$1.invoke(Main.kt:59)
	at ftl.Main$Companion$main$1.invoke(Main.kt:51)
	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:21)
	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:12)
	at ftl.Main$Companion.main(Main.kt:54)
	at ftl.Main.main(Main.kt)
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Expected not to crash.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
$ flank --version
version: local_snapshot
revision: a007f6c7fbe67f138eb41c9d0dd812b8230acabb
session id: a84d5a7a-6ebf-473d-a308-f5693e141ff3
```

**Additional context**
> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1601 

When use  ```--dump-shards```, flank should create dump shard file without errors. 

## Checklist

- [X] Unit tested
- [X] Integration tests updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/run/DumpShards.kt [hunk 1]
```diff
@@ -71,7 +71,10 @@ fun saveShardChunks(
     )
     logLn("${FtlConstants.indent}Saved $size shards to $shardFilePath", OutputLogLevel.DETAILED)
 }
-private fun String.createDirectories() = File(this).parent.toFile().mkdirs()
+
+private fun String.createDirectories() = takeIf { it !in listOf(ANDROID_SHARD_FILE, IOS_SHARD_FILE) }?.let {
+    File(this).parent.toFile().mkdirs()
+}
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/run/DumpShards.kt:77]:
```suggestion
private fun String.createDirectories() {
    if (this !in listOf(ANDROID_SHARD_FILE, IOS_SHARD_FILE))
        File(this).parent.toFile().mkdirs()
}
```

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        ).run(
+            workingDirectory = "./",
+            testSuite = name
+        )
+
+        assertExitCode(result, 0)
+
+        val resOutput = result.output.removeUnicode()
+        Truth.assertThat(resOutput).containsMatch(findInCompare(name))
+        assertNoOutcomeSummary(resOutput)
```
Comment (pawelpasterz) [inline integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:29]: It would be great if the test verifies the content of created JSON as well

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
```
Comment (pawelpasterz) [inline integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:49]: Same as previous, let's check what JSON has inside

File: integration_tests/src/test/resources/cases/dump_shards_android.yml [hunk 4]
```diff
@@ -0,0 +1,3 @@
+gcloud:
```
Comment (pawelpasterz) [inline integration_tests/src/test/resources/cases/dump_shards_android.yml:1]: I think we should add configuration with actual sharding applied, 2-3 shards should be enough.

File: integration_tests/src/test/resources/cases/dump_shards_android.yml [hunk 5]
```diff
@@ -0,0 +1,3 @@
...
+  app: ../test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
+  test: ../test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-success-debug-androidTest.apk
```
Comment (pawelpasterz) [inline integration_tests/src/test/resources/cases/dump_shards_android.yml:3]: Let's switch to multiple success apk, it contains ignored and parameterized classes. The test should also verify if ignored tests are placed in the 'ignored section' in JSON

File: integration_tests/src/test/resources/cases/dump_shards_ios.yml [hunk 6]
```diff
@@ -0,0 +1,4 @@
+gcloud:
```
Comment (pawelpasterz) [inline integration_tests/src/test/resources/cases/dump_shards_ios.yml:1]: Similar here, let's add sharding

**Review by pawelpasterz — CHANGES_REQUESTED** [review]
I think it would be great to cover more cases within tests. For JSON verification, I think we should verify if ignored tests are present in the right place but also if the number of shards is correct. We should also check if the total number of tests is correct

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt (hunk 2 above)
Comment (adamfilipow92) [reply integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:29]: Agree but I was thinking about creating an epic to add JSON verification for all integration tests. But on the other hand, adding JSON verification here could be a good start point for other tests. WDYT?

Comment (pawelpasterz) [reply integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:29]: Fine for me

Comment (pawelpasterz) [reply integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:29]: For clarification, I meant JSON with shards, not the one introduced on https://github.com/Flank/flank/pull/1559

**Review by Sloox — COMMENTED** [review]
Has it been tested on Windows ;)

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt (hunk 3 above)
Comment (adamfilipow92) [reply integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:75]: Added

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt (hunk 2 above)
Comment (adamfilipow92) [reply integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:33]: > Has it been tested on Windows ;)

Tested and works :)

**Comment by adamfilipow92** [comment]
> Has it been tested on Windows ;)

Tested and works :)

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+
+        Truth.assertThat(matrix.shards.values.flatten()).containsAll(
+            "class com.example.test_app.parametrized.EspressoParametrizedClassParameterizedNamed",
+            "class com.example.test_app.parametrized.EspressoParametrizedClassTestParameterized",
+            "class com.example.test_app.ParameterizedTest",
+            "class com.example.test_app.parametrized.EspressoParametrizedMethodTestJUnitParamsRunner",
+        )
+
+        Truth.assertThat(matrix.junitIgnored.count()).isEqualTo(4)
+        Truth.assertThat(matrix.junitIgnored).containsNoDuplicates()
```
Comment (pawelpasterz) [inline integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:47]: Good idea! 👍

File: integration_tests/src/test/kotlin/integration/DumpShardsIT.kt [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+        val matrix = File("android_shards.json").loadAndroidDumpShards()
+
+        Truth.assertThat(matrix.shards.count()).isEqualTo(2)
+
+        Truth.assertThat(matrix.shards.values.flatten()).containsAll(
+            "class com.example.test_app.parametrized.EspressoParametrizedClassParameterizedNamed",
+            "class com.example.test_app.parametrized.EspressoParametrizedClassTestParameterized",
+            "class com.example.test_app.ParameterizedTest",
+            "class com.example.test_app.parametrized.EspressoParametrizedMethodTestJUnitParamsRunner",
+        )
```
Comment (pawelpasterz) [inline integration_tests/src/test/kotlin/integration/DumpShardsIT.kt:44]: I like the test checks if there are tests inside shards 👍 We could make one step further and check if there are all tests or we can check just the number. (test count does not change and we check for duplication in another line)

**Review by pawelpasterz — APPROVED** [review]

**Review by Sloox — APPROVED** [review]
LGTM 🚀
