### PR TITLE
fix: cancelCommandRuns should works independent

### LINKED ISSUE #1403: CancelCommandTest is failing on ubuntu workflow
**Describe the bug**
> A clear and concise description of what the bug is.

`CancelCommandTest` is failing on the ubuntu workflow because of missing `results/a/matrix_ids.json`.

**To Reproduce**
> Steps to reproduce the behavior:

CI: 
1. Create a pull request
1. Expect failed test in ubuntu workflow like that https://github.com/Flank/flank/runs/1562332906#step:6:260

Locally:
1. Clear the `results` directory
1. Run only `CancelCommandTest.cancelCommandRuns`
1. Expect failure like that https://github.com/Flank/flank/runs/1562332906#step:6:260

**Expected behavior**
> A clear and concise description of what you expected to happen.

The test should create `matrix_ids.json` on-demand before running `CancelCommand`.

**Additional context**
> Add any other context about the problem here.

This test is flaky in some situations. Can pass if `results/a/matrix_ids.json` already exists, possibly created by another test before.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1403 

### I case

1. If exist remove ```test_runner/results```
1. run only ```CancelCommandTest.cancelCommandRuns``` test
1. Test should pass

### II case

1. If exist remove ```test_runner/results```
1. run ```./gradlew check```
1. Test should pass

### III case

1. You should have ```test_runner/results``` with some subdirectories with test results
1. Check ```test_runner/results``` contains ```a``` directory without ```matrix_ids.json```. This directory cause problem on Ubuntu workflow. Remove rest of directories (```test_runner/results``` should contain only ```a``` directory)
1. run only ```CancelCommandTest.cancelCommandRuns``` test
1. Test should pass

- [x] Ubuntu workflow should pass

### CODE REVIEW

File: test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt [hunk 1]
```diff
@@ -43,7 +43,6 @@ class CancelCommandTest {
 
     @Test
     fun cancelCommandRuns() {
-        CancelCommand().run()
```
Comment (Sloox) [inline test_runner/src/test/kotlin/ftl/cli/firebase/CancelCommandTest.kt:46]: Nice change ;)

**Review by Sloox — APPROVED** [review]

**Review by pawelpasterz — APPROVED** [review]
