### PR TITLE
fix: Shards and Tests count do not match

### LINKED ISSUE #986: Test count and smart sharding count dont match
**Describe the bug**
> A clear and concise description of what the bug is.

Test result shows app module has 349 tests but smart sharding show and calculate with 232.

**To Reproduce**
> Steps to reproduce the behavior:

It happens with out project. i dont have a repo to share.

**Expected behavior**
> A clear and concise description of what you expected to happen.

Test result and smart sharding should have same count.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Flank 20.08.1
In the repo, there are Ignored, suppressed and parameterized tests.
With no orchectrator

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #986 

In case when we using parameterized tests, flank should inform the user how many parameterized class have.

```txt

 Smart Flank cache hit: 0% (0 / 9)
  Shard times: 240s, 240s, 240s, 360s

  Uploading app-debug.apk .
  Uploading app-multiple-flaky-debug-androidTest.apk .
  5 tests + 4 parameterized classes / 4 shards

```

## Checklist

- [X] Documented
- [X] Unit tested

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt [hunk 1]
```diff
@@ -148,6 +149,9 @@ data class CommonFlankConfig @JsonIgnore constructor(
     @set:JsonProperty("default-test-time")
     var defaultTestTime: Double? by data
 
+    @set:JsonProperty("default-class-test-time")
+    var defaultClassTestTime: Double? by data
```
Comment (kozaxinan) [inline test_runner/src/main/kotlin/ftl/config/common/CommonFlankConfig.kt:153]: Does `keys` list need this new value to be able to check by flank doctor? `defaultTestTime` is also missing in `key` list.

File: test_runner/src/main/kotlin/ftl/run/DumpShards.kt [hunk 2]
```diff
@@ -35,7 +35,7 @@ fun dumpShards(
 ) {
     saveShardChunks(
         shardFilePath = shardFilePath,
-        shards = args.testShardChunks,
+        shards = args.testShardChunks.map { it.testsList },
```
Comment (kozaxinan) [inline test_runner/src/main/kotlin/ftl/run/DumpShards.kt:38]: nit: `testShardChunks.map { it.testsList }` method chain is repeated a couple of places, would it be better to have extension function for mappinig testsList?

File: docs/bugs/986_test_count_and_smart_sharding_ count_dont_match.md [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+1. Flank known how many test and classes are sent to Firebase. So we can inform the user how many classes we have. Example:
+
+```txt
+
+ Smart Flank cache hit: 0% (0 / 9)
+  Shard times: 240s, 240s, 240s, 360s
+
+  Uploading app-debug.apk .
+  Uploading app-multiple-flaky-debug-androidTest.apk .
+  5 tests + 4 classes / 4 shards
```
[the remark this answers is not in the document]
Comment (pawelpasterz) [reply docs/bugs/986_test_count_and_smart_sharding_ count_dont_match.md:30]: Right, I forgot to add `parameterized` 👍

**Review by jan-gogo — APPROVED** [review]

**Review by piotradamczyk5 — APPROVED** [review]
