### PR TITLE
Fix crash when --legacy-junit-result set

### LINKED ISSUE #947: If --legacy-junit-result set, flank crashing on report uploading
**Describe the bug**
> A clear and concise description of what the bug is.

If --legacy-junit-result set, flank crashing on report uploading

**To Reproduce**
> Steps to reproduce the behavior:

1. Run flank with flag ``` --legacy-junit-result ```
2. When flank tries to upload report throws an exception.

```
FetchArtifacts
  .
  Updating matrix file

java.lang.NullPointerException
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:272)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at ftl.reports.util.ReportManager.getWebLink(ReportManager.kt:51)
	at ftl.reports.util.ReportManager.processXmlFromFile$flank(ReportManager.kt:81)
	at ftl.reports.util.ReportManager.parseTestSuite(ReportManager.kt:100)
	at ftl.reports.util.ReportManager.generate(ReportManager.kt:111)
	at ftl.run.NewTestRunKt$newTestRun$2.invokeSuspend(NewTestRun.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at ftl.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:47)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at DebugKt$main$1.invoke(Debug.kt:19)
	at DebugKt$main$1.invoke(Debug.kt)
	at ftl.util.Utils.withGlobalExceptionHandling(Utils.kt:130)
	at DebugKt.main(Debug.kt:18)
	at DebugKt.main(Debug.kt)

Process finished with exit code 1

```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank, shouldn't throw an exception on uploading legacy JUnit result

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?

Tested on latest master

This issue is related to [Issue 157](https://github.com/runningcode/fladle/issues/157) because without it we cannot use ```--legacy-junit-result```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #947 

When using --legacy-junit-result flank, shouldn't throw an exception. 

## Checklist

- [X] Unit tested
- [X] release_notes.md updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt [hunk 1]
```diff
@@ -40,25 +39,11 @@ object ReportManager {
...
-            webLink = savedMatrix.webLink
-        } else {
-            println("WARNING: Matrix path not found in JSON. $matrixPath")
-        }
-        return webLink
-    }
+    private fun getWebLink(matrices: MatrixMap, xmlFile: File): String = xmlFile.getMatrixPath(matrices.runPath)
+        ?.let { path ->
+            matrices.map.values.firstOrNull { savedMatrix -> savedMatrix.gcsPath.endsWith(path) }?.webLink
+                ?: "".also { println("WARNING: Matrix path not found in JSON. $path") }
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt:45]: Could you extract this to separate method for better readability?

Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt]: Changed!
