### PR TITLE
#850 fix printing all matrix links

### LINKED ISSUE #850: Not all errored matrix links printed
**Describe the bug**
Only the first matrix link is printed at the end of the run. Instead we should print links to all failed matrices to enable easy investigation of failures.

**To Reproduce**

Run `flank android run`

```yaml
gcloud:
  app: ../test_app/apks/app-debug.apk
  test: ../test_app/apks/app-debug-androidTest.apk
  num-flaky-test-attempts: 2

flank:
  max-test-shards: 2
  additional-app-test-apks:
   - test: ../test_app/apks/error-androidTest.apk
```

```

Matrices webLink
  matrix-1evibpy3p9sxt https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/5347982549609255244
  matrix-3hploc89vyprr https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/7008313042603917078/executions/bs.98bc447c06966582

  2m 39s matrix-3hploc89vyprr NexusLowRes-28 shard-0 execution-22scboa5ytagw FINISHED
  2m 39s matrix-3hploc89vyprr NexusLowRes-28 shard-0 execution-22scboa5ytagw FINISHED
  2m 24s matrix-1evibpy3p9sxt NexusLowRes-28 shard-1 execution-21mw6w55wsyhu FINISHED
  2m 39s matrix-1evibpy3p9sxt NexusLowRes-28 shard-0 execution-qpt49dx7errqa FINISHED
  4m 43s matrix-1evibpy3p9sxt NexusLowRes-28 shard-1 execution-3kur0xdkrli7g FINISHED
  4m 53s matrix-1evibpy3p9sxt NexusLowRes-28 shard-1 execution-2fpx2ajxn51ag FINISHED
  4m 53s matrix-3hploc89vyprr FINISHED
  4m 53s matrix-1evibpy3p9sxt FINISHED

FetchArtifacts
  .....
  Updating matrix file

CostReport
  Virtual devices
    $0.08 for 5m

MatrixResultsReport
  1 / 2 (50.00%)
  1 matrices failed

More details are available at [https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/7008313042603917078]
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ success │  matrix-3hploc89vyprr  │                    │
│ failure │  matrix-1evibpy3p9sxt  │                    │
└─────────┴────────────────────────┴────────────────────┘
  Uploading JUnitReport.xml .
```

**Expected behavior**
I expect `More details are available at[ ... ]` to include links to all failed matrices.
https://github.com/Flank/flank/blob/c88cb2786de67c0a114fc31a7b25917a035e145b/test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt#L49-L50

Currently only the first matrix is printed. In this case, the link to the successful matrix is printed which is not helpful for debugging the failures.

**Details (please complete the following information):**
 - Have you tested on the latest Flank snapshot?
 - Post the output of ` flank --version`.

```
flank --version
version: local_snapshot
revision: aea1e676c7cf2a34388152803a6e5ba866c2bca4
```

**Additional context**

When matrices fail, we should provide as much information as possible to make it easy for users to understand what's going on.

### PR DESCRIPTION
**Pull request by piotradamczyk5**
Fixes #850 

All matrices failed links are printed in summary below the summary table.
Do not print any data if there are not present failed links.

## Checklist

- [x] Unit tested
- [x] release_notes.md updated

### CODE REVIEW

**Comment by bootstraponline** [comment]
> All matrices links are printed in summary

We want to print only links to failed matrices, not all. The goal is to make it as easy as possible to investigate failures.

**Comment by piotradamczyk5** [comment]
> > All matrices links are printed in summary
> 
> We want to print only links to failed matrices, not all. The goal is to make it as easy as possible to investigate failures.

Fixed to print only failures matrices

File: test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt [hunk 1]
```diff
@@ -48,14 +49,23 @@ object MatrixResultsReport : IReport {
...
+                val savedMatrices = matrices.map.values
+                writer.println(savedMatrices.toList().asPrintableTable())
+                savedMatrices.printMatricesLinks(writer)
             }
 
             return writer.toString()
         }
     }
 
+    private fun Collection<SavedMatrix>.printMatricesLinks(writer: StringWriter) {
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt:61]: Here is my proposal for formatting. I am just not a big fan of multiple `?.` chain calls. Of course, it's not change request. Just let me know what do you think
```suggestion
    private fun Collection<SavedMatrix>.printMatricesLinks(writer: StringWriter) = this
        .filter { it.failed() }
        .takeIf { it.isNotEmpty() }
        ?.run { this
            .also { writer.println("More details are available at:") }
            .map { it.webLinkWithoutExecutionDetails }
            .forEach { writer.println(it) }
        }
```

Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt:61]: I personally preferer to avoid nested operations in block, that's why I changed it to `?.` chain (previous version looks like yours :) )

Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt:61]: Got your point. We can still make it simpler skip one `map` operation and just invoke `forEach { writer.println(it.webLinkWithoutExecutionDetails) }`

**Comment by pawelpasterz** [comment]
Maybe we could add new line or other separator below links? It's cosmetic change but would improve clarity of logs
Screenshot 2020-07-01 at 10 50 19

**Comment by piotradamczyk5** [comment]
> Maybe we could add new line or other separator below links? It's cosmetic change but would improve clarity of logs
> Screenshot 2020-07-01 at 10 50 19

so in that case, you code without `?.` will look better :)

File: test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt (hunk 1 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt]: applied your suggestion, because of new line comment :)
