### PR TITLE
fix: Fix missing junit report in legacy mode

### LINKED ISSUE #1778: Missing `JUnitReport` with legacy mode
**Describe the bug**
> A clear and concise description of what the bug is.

Flank is missing XML results when `legacy-junit-result: true`

**To Reproduce**
> Steps to reproduce the behavior:

1. Run any android flank test run, just add `legacy-junit-result: true` to the config file
2. Wait until tests are finished
3. Observe no result XML file is generated

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank should generate `JUnitReport.xml`. We should verify if results are generated for iOS.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: local_snapshot
revision: 7e83bd79f7dfee9521b84ae68c1d351500d42624
session id: ee89af15-635e-4a7c-8f23-2f4a0e02981a
```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1778 

All tests should pass, when using android tests with legacy mode Flank should generate JUnitReport in the results directory, performance metrics file should be created.

This pr is a revert of @piotradamczyk5 change related to ```performanceMetrics.json``` creation. I was checking this feature and still works fine. 

To test if ```performanceMetrics.json```  are created:

1. Run any test case with a physical device for e.g.
```  
device:
    - model: starqlteue
      version: 26
```

1.  Check if the Flank output contains a line about uploading ```performanceMetrics.json``` to gcs

```
 Uploading [performanceMetrics.json] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-04-19_07-59-02.195180_AbIK/matrix_0/...
```

1. Check if local matrix directories contain ```performanceMetrics.json``` 

1. Run the same Flank configuration on the current master and compare ```performanceMetrics.json```.

## Test results

```yml

gcloud:
  app: ./test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
  test: ./test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-success-debug-androidTest.apk
  device:
    - model: starqlteue
      version: 26

flank:
  disable-sharding: true
  output-report: json

```

1.  ```performanceMetrics.json``` from this branch [link](https://console.cloud.google.com/storage/browser/_details/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-04-19_08-38-03.546503_fWjv/matrix_0/performanceMetrics.json)

1. ```performanceMetrics.json``` from current master [link](https://console.cloud.google.com/storage/browser/_details/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-04-19_08-57-35.859011_MpIb/matrix_0/performanceMetrics.json?authuser=1)

## Checklist

- [X] Integration tests updated

### CODE REVIEW

**Comment by adamfilipow92** [comment]
@flank-it

File: integration_tests/src/test/kotlin/integration/LegacyResultIT.kt [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import utils.assertTestCountMatches
+import utils.findTestDirectoryFromOutput
+import utils.firstTestSuiteOverview
+import utils.iosRunCommands
+import utils.json
+import utils.removeUnicode
+import utils.toJUnitXmlFile
+import utils.toOutputReportFile
+
+class LegacyResultIT {
```
Comment (piotradamczyk5) [inline integration_tests/src/test/kotlin/integration/LegacyResultIT.kt:22]: please check `Truth` import in this file

**Review by piotradamczyk5 — APPROVED** [review]

**Comment by adamfilipow92** [comment]
@flank-it

**Review by jan-gogo — APPROVED** [review]
