### PR TITLE
#787 More error messages improvements

### LINKED ISSUE #787: More improvments in error messages
Based of @pawelpasterz suggestion here: https://github.com/Flank/flank/pull/780#issuecomment-628859722 maybe we should handle more cases. Even if messages of them are better we could make some changes and convert them to one generic excepion for parsing errors like FlankConfigurationException.
Let me all know what you think.
@bootstraponline @pawelpasterz @jan-gogo

### PR DESCRIPTION
**Pull request by piotradamczyk5**
Fixes #787 

Check error messages when YAML tree is bad (example in file `flank-bad-yaml-formatting.yml`)
Unit tests describe current behavior

## Checklist

- [x] Unit tested
- [x] release_notes.md updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt [hunk 1]
```diff
@@ -13,3 +14,8 @@ fun convertConfigurationErrorExceptions(missingParameterError: Exception, yaml:
         missingParameterError
     }
 }
+
+fun convertConfigurationErrorExceptions(treeParsingException: MarkedYAMLException): Throwable {
+    val errorMessageBuilder = ConfigurationErrorMessageBuilder
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt:19]: If `ConfigurationErrorMessageBuilder.invoke` will be a top level function, this assignment wouldn't be needed ;).

File: test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-bad-yaml-formatting.yml [hunk 2]
```diff
@@ -0,0 +1,214 @@
+# gcloud args match the official gcloud cli
+# See the docs for full gcloud details https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run
```
Comment (jan-gogo) [inline test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-bad-yaml-formatting.yml:2]: the comments are not necessary

File: test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt (hunk 1 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt:19]: I would like to have it consistent with previous message builder, however I move it to single line

File: test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-bad-yaml-formatting.yml (hunk 2 above)
Comment (piotradamczyk5) [reply test_runner/src/test/kotlin/ftl/args/yml/test_error_yaml_cases/flank-bad-yaml-formatting.yml]: comments removed

File: test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt (hunk 1 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/args/yml/YamlErrorConverter.kt]: to make this consistent I leave this in ConfigurationErrorMessageBuilder, but changed to a single line and avoid assignment

File: test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt [hunk 3]
```diff
@@ -78,6 +83,34 @@ Error node: {
         Assert.assertEquals(exceptedMessage, actualMessage)
     }
 
+    @Test
+    fun `Should properly build error message from MarkedYAMLException`() {
```
Comment (adamfilipow92) [inline test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt:87]: Rest of functions starts from lower letter.

Comment (piotradamczyk5) [reply test_runner/src/test/kotlin/ftl/args/yml/ErrorParserTest.kt]: fixed
