### PR TITLE
fix: Fix printing supported versions id 

### LINKED ISSUE #1328: Supported version ids for device printed not correctly
**Describe the bug**
> A clear and concise description of what the bug is.

When a user try to use the device with an unsupported API level flank prints message

```

Incompatible model, 'OnePlus5', and version, '28'
Supported version ids for 'OnePlus5': ftl.android.IncompatibleModelVersion@1fde0371

```

**To Reproduce**
> Steps to reproduce the behavior:

1. Run flank with the device configured with unsupported API level like
```

  device:
    - model: OnePlus5
      version: 28

```

2. See error

```

Incompatible model, 'OnePlus5', and version, '28'
Supported version ids for 'OnePlus5': ftl.android.IncompatibleModelVersion@1fde0371

```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank should print supported versions correctly.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Latest master

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1328 

1. Run Flank with a configured device with not supported API level

```
  device:
    - model: OnePlus6T
      version: 19

```

or if you want to check how the message looks when we have more than one supported version

```

  device:
    - model: Nexus7
      version: 28

```

2. Error message should look like:

```

Incompatible model, 'OnePlus6T', and version, '19'
Supported version ids for 'OnePlus6T': 28


```

## Checklist

- [X] Fix printing on android
- [x] Verification and fix iOs
- [X] Unit tested

### CODE REVIEW

**Review by axelzuziak-gogo — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt [hunk 1]
```diff
@@ -66,7 +67,7 @@ private fun IosArgs.assertXcodeSupported() = when {
 
 private fun IosArgs.assertDevicesSupported() = devices.forEach { device ->
     if (!IosCatalog.supportedDevice(device.model, device.version, this.project))
-        throw IncompatibleTestDimensionError("iOS ${device.version} on ${device.model} is not a supported device")
+        throw IncompatibleTestDimensionError("iOS ${device.version} on ${device.model} is not a supported\nSupported version ids for '${device.model}': ${device.getSupportedVersionId(project).joinToString { it }}")
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/args/ValidateIosArgs.kt:70]: ).joinToString()
```suggestion
        throw IncompatibleTestDimensionError("iOS ${device.version} on ${device.model} is not a supported\nSupported version ids for '${device.model}': ${device.getSupportedVersionId(project).joinToString()}")
```

**Review by piotradamczyk5 — APPROVED** [review]
