### PR TITLE
fix: Print Flank version only on run command

### LINKED ISSUE #1561: Only print flank version on Run command
**Describe the bug**
> A clear and concise description of what the bug is.

Every command starts by printing the flank version. I think only the run command should start by printing the version.

The workflow is someone runs Flank and then wants to know what version of flank was used to execute the tests. I don't think it makes sense to print the flank version on `flank provided-software list` for example.

**To Reproduce**
> Steps to reproduce the behavior:

1. Run `flank provided-software list`
2. See the version is printed

```
$ flank provided-software list
version: local_snapshot
revision: ae09391820ab7facaaa5b7679876e9ae2c0edaed
session id: 39f08992-c5c8-4f61-9fb2-e61aea7f7a97

┌──────────────────────┐
│ ORCHESTRATOR VERSION │
├──────────────────────┤
│ 1.0.2                │
└──────────────────────┘
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

No version printed unless we are invoking a `flank run ...` command or the version command directly.

```
$ flank provided-software list

┌──────────────────────┐
│ ORCHESTRATOR VERSION │
├──────────────────────┤
│ 1.0.2                │
└──────────────────────┘
```

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
flank --version
version: local_snapshot
revision: ae09391820ab7facaaa5b7679876e9ae2c0edaed
session id: 35f6c8a1-2f32-44b7-963d-62b7ff1c6933
```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1561 

## I case

1. Run android or ios test
1. Flank should print version, revision, and sessionId 

## II case

1. Run Flank with ```--version```
1. Flank should print version, revision, and sessionId 

## III case

1. Run a command like ```flank provided-software list````
1. Version information should not be printed.

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/util/Utils.kt [hunk 1]
```diff
@@ -68,6 +69,13 @@ private fun getResource(name: String): InputStream {
         ?: throw FlankGeneralError("Unable to find resource: $name")
 }
 
+fun printVersionInfo() {
+    logLn("version: " + readVersion())
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/util/Utils.kt:73]:
```suggestion
    logLn("version:${readVersion}")
```
?
The same for all 2 lines below?

File: test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt [hunk 2]
```diff
@@ -59,6 +60,9 @@ class AndroidRunCommand : CommonRunCommand(), Runnable {
     }
 
     override fun run() {
+
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt:63]: hmmm do you have git pre commit working? :)

**Review by Sloox — CHANGES_REQUESTED** [review]

File: test_runner/src/main/kotlin/ftl/util/Utils.kt (hunk 1 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/util/Utils.kt]: Thanks! Changed!

File: test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt (hunk 2 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/cli/firebase/test/android/AndroidRunCommand.kt]: Yes, but pre commit hook not catch that. I removed this line! Thanks!

**Comment by pawelpasterz** [comment]
It would be great to have a couple of tests to verify it?

**Comment by adamfilipow92** [comment]
> It would be great to have a couple of tests to verify it, do you think it requires lots of work to implement it?

Right! Tests added! 👍

**Review by piotradamczyk5 — APPROVED** [review]
Tested few commands (`flank ios versions list`, `flank android models list`, `flank network-profiles list`) and middle command (help of groups) - version is not printed
Tested (`flank -v `, `flank android run`, `flank ios run`) - Version is printed

Code looks good 👍

**Review by jan-gogo — CHANGES_REQUESTED** [review]
I love that now we are absolutely sure that the version will not be printed in other commands than run, but IMO from a maintenance perspective, it's a bad idea to have a test for checking that something wasn't occurring. Do you know what I mean? There is an infinite number of things that cannot occur in flank runtime, we shouldn't focus on them.

**Review by jan-gogo — APPROVED** [review]

**Review by Sloox — APPROVED** [review]
