### PR TITLE
#816 Omit `environment-variables` for robo test executions instead of throwing exception.

### LINKED ISSUE #816: Better validation for unsupported params in robo test
Hi folks, I was running a robo test and got the following message
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Environment Variables not supported on Android Robo tests",
    "reason" : "badRequest"
  } ],
  "message" : "Environment Variables not supported on Android Robo tests",
  "status" : "INVALID_ARGUMENT"
}
```

It would be helpful to fail fast and save the uploading of the apks when a request is going to come back invalid. Specifically I would like validation added for invalid arguments. when. running robotests (please and thank you)

Enjoy your day

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #816

## Checklist

- [X] Unit tested
- [X] release_notes.md updated

### CODE REVIEW

**Comment by adamfilipow92** [comment]
Now i have added fast fail for environment-variables. In testlab docs I cannot find any information about unsupported params in robo test. Maybe anyone have more informations?
@pawelpasterz @jan-gogo @bootstraponline @piotradamczyk5

**Comment by bootstraponline** [comment]
> Now i have added fast fail for environment-variables. In testlab docs I cannot find any information about unsupported params in robo test. Maybe anyone have more informations?

That's a great question. I think it's mostly trial and error at this point. We could also ask on #test-lab in the https://firebase.community/ Slack.

File: test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt [hunk 1]
```diff
@@ -1362,6 +1362,24 @@ AndroidArgs
             )
         }
     }
+
+    @Test(expected = FlankFatalError::class)
+    fun `should fast fail wen robo test have env variables set`() {
```
Comment (bootstraponline) [inline test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt:1367]:
```suggestion
    fun `should fast fail when the robo test has env variables set`() {
```

File: test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt [hunk 2]
```diff
@@ -131,7 +131,9 @@ class AndroidArgs(
         if (roboDirectives.isNotEmpty() && roboScript != null) throw FlankFatalError(
             "Options robo-directives and robo-script are mutually exclusive, use only one of them."
         )
-
+        if (isRoboTest && environmentVariables.isNotEmpty()) throw FlankFatalError(
+            "Environment Variables not supported on Android Robo tests"
```
Comment (bootstraponline) [inline test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt:135]:
```suggestion
            "Environment variables are not currently supported on Android Robo tests"
```

File: release_notes.md [hunk 3]
```diff
@@ -10,7 +10,7 @@
 - [#812](https://github.com/Flank/flank/issues/812) Convert bitrise macOS workflow to github action. ([piotradamczyk5](https://github.com/piotradamczyk5))
 - [#799](https://github.com/Flank/flank/pull/799) Refactor Shared object by splitting it into smaller functions. ([piotradamczyk5](https://github.com/piotradamczyk5))
 - [#798](https://github.com/Flank/flank/pull/798) Remove failure nodes from tests that passed on retry so that Jenkins JUnit plugin marks them as successful. ([adamfilipow92](https://github.com/adamfilipow92))
-- 
+- [#826](https://github.com/Flank/flank/pull/826) Fast fail for unsupported params in robo test. ([adamfilipow92](https://github.com/adamfilipow92))
```
Comment (bootstraponline) [inline release_notes.md:13]:
```suggestion
- [#826](https://github.com/Flank/flank/pull/826) Fast fail when using `environment-variables` in a robo test. ([adamfilipow92](https://github.com/adamfilipow92))
```

**Comment by adamfilipow92** [comment]
> > Now i have added fast fail for environment-variables. In testlab docs I cannot find any information about unsupported params in robo test. Maybe anyone have more informations?
> 
> That's a great question. I think it's mostly trial and error at this point. We could also ask on #test-lab in the https://firebase.community/ Slack.

Today, I checked #test-lab and I seen your thread. We got information about rest of TestSetup variables. "All of the other options in TestSetup etc should work for any test type." So maybe we should dedicate this pull request for `environment-variables` and if in thread we get more informations we make new issue. Additionally I checked this docs: https://firebase.google.com/docs/test-lab/reference/testing/rest/v1/projects.testMatrices#environmentvariable
I can't found more informations about unsupported variables in any test type.

**Comment by pawelpasterz** [comment]
@bootstraponline 
With #817 flank gained ability to run both robo and instrumentation tests within one run. With this fail fast approach this feature will impossible to use if one wants to have env variables. Is it something we agree on?

**Comment by jan-gogo** [comment]
> @bootstraponline
> With #817 flank gained ability to run both robo and instrumentation tests within one run. With this fail fast approach this feature will impossible to use if one wants to have env variables. Is it something we agree on? (I think it is more like design decision)

Maybe it's possible to just omit env variables for robo test executions instead of throwing exception?

**Comment by pawelpasterz** [comment]
> Maybe it's possible to just omit env variables for robo test executions instead of throwing exception? Exceptions are good when there are missing data but here we have additional data that is probably not needed for robo tests.

That was my idea as well, +1 for this

**Comment by bootstraponline** [comment]
> Maybe it's possible to just omit env variables for robo test executions instead of throwing exception? Exceptions are good when there are missing data but here we have additional data that is probably not needed for robo tests.

That makes sense to me. In the future, FTL may add env variable support for Robo tests. At that time, we'll want to remove this.

File: test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt [hunk 4]
```diff
@@ -131,7 +131,9 @@ class AndroidArgs(
         if (roboDirectives.isNotEmpty() && roboScript != null) throw FlankFatalError(
             "Options robo-directives and robo-script are mutually exclusive, use only one of them."
         )
-
+        if (isRoboTest && environmentVariables.isNotEmpty()) throw FlankFatalError(
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt:134]: omit env variables for robo test executions instead of throwing exception

File: test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt [hunk 5]
```diff
@@ -28,6 +29,15 @@ object GcAndroidTestMatrix {
         value = this@toEnvironmentVariable.value
     }
 
+    @VisibleForTesting
+    internal fun TestSetup.setEnvironmentVariables(args: AndroidArgs, testConfig: AndroidTestConfig) = this.apply {
+        environmentVariables = if (args.environmentVariables.isNotEmpty() && testConfig is AndroidTestConfig.Instrumentation) {
+            args.environmentVariables.map { it.toEnvironmentVariable() }
+        } else {
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt:36]: braces are redundant for this if-else expression

File: test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt [hunk 6]
```diff
@@ -28,6 +29,15 @@ object GcAndroidTestMatrix {
         value = this@toEnvironmentVariable.value
     }
 
+    @VisibleForTesting
+    internal fun TestSetup.setEnvironmentVariables(args: AndroidArgs, testConfig: AndroidTestConfig) = this.apply {
+        environmentVariables = if (args.environmentVariables.isNotEmpty() && testConfig is AndroidTestConfig.Instrumentation) {
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt:34]: `args.environmentVariables.isNotEmpty()` is redundant check, because is nothing wrong with running `args.environmentVariables.map { it.toEnvironmentVariable() }` on empty args

File: test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt [hunk 7]
```diff
@@ -28,6 +29,15 @@ object GcAndroidTestMatrix {
         value = this@toEnvironmentVariable.value
     }
 
+    @VisibleForTesting
+    internal fun TestSetup.setEnvironmentVariables(args: AndroidArgs, testConfig: AndroidTestConfig) = this.apply {
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/gc/GcAndroidTestMatrix.kt:33]: This extension deserves for dedicated file. Check out `setupAndroidTest` for example.

File: test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt [hunk 8]
```diff
@@ -692,9 +691,9 @@ AndroidArgs
         gcloud:
           app: $appApk
           test: $testApk
-          num-uniform-shards: ${AVAILABLE_SHARD_COUNT_RANGE.last}
+          num-uniform-shards: 50
         flank:
-          max-test-shards: ${AVAILABLE_SHARD_COUNT_RANGE.last}
+          max-test-shards: 50
```
Comment (piotradamczyk5) [inline test_runner/src/test/kotlin/ftl/args/AndroidArgsTest.kt:696]: it should be merged with latest master
