### PR TITLE
fix: #842 support for test targets flag in multiple testbundles xctest

### LINKED ISSUE #842: Tests are included in XCTest entries that do not contain the test
**Describe the bug**
If the original xctestrun has multiple XCTest entries, Tests included via `--test-targets` flag will be added to the `OnlyTestIdentifiers` array on every XCTest entry, not just the one(s) that actually includes that test.

**To Reproduce**
Start with a xctestrun that has multiple xctests:
e.g.
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
        </dict>
	<key>TestSuiteB</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteB.xctest</string>
        </dict>
</dict>
```

and run flank over that xctestrun with `--test-targets` for a test within only one of those suites, e.g. `ClassB/methodC` as a part of SuiteA

**Expected behavior**
Flank should produce main_shard_0.xctestrun that contains:
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
</dict>
```

**Details (please complete the following information):**
Flank produces main_shard_0.xctestrun instead that contains:
```
<plist version="1.0">
<dict>
	<key>TestSuiteA</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteA.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
	<key>TestSuiteB</key>
	<dict>
		<key>TestBundlePath</key>
		<string>__TESTHOST__/PlugIns/TestSuiteB.xctest</string>
		<key>OnlyTestIdentifiers</key>
		<array>
			<string>ClassB/methodC</string>
		</array>
        </dict>
</dict>
```

Version:
```
$ java -jar tools/flank/flank-v20.05.2.jar --version
version: v20.05.2
revision: 7618ebdb5a74db4b448de0b93357221de3ab10c2
```

.yml config:
```
gcloud:
  record-video: true
  timeout: 10m
  async: false
  # iOS gcloud
  test: FirebasePayload.zip
  xctestrun-file: FirebasePayload/main.xctestrun
  xcode-version: 11.3.1
  device:
    - model: iphone8
      version: 12.0
      locale: en
  results-history-name: ios-flank
flank:
  max-test-shards: 50
  num-test-runs: 1
```

### PR DESCRIPTION
**Pull request by axelzuziak-gogo**
Fixes #842

## Describe the bug
If the original .xctestrun has multiple XCTest entries, Tests included via --test-targets flag will be added to the OnlyTestIdentifiers array on every XCTest entry, not just the one(s) that actually includes that test.
__
Currently Flank rewrites whole .xctestrun file with methods specified --test-targets without checking whether those methods actually exists in XCTest. This solution works fine for a .xctestrun files containing only one XCTest. 

## Solution
Flank now rewrites .xctestrun with mapping correct methods names with specific XCTests.

- unit tested
- new test artifacts with multiple XCTest entries

## Checklist

- [x] Documented
- [x] Unit tested
- [x] Test artifacts added to TestProjects

### CODE REVIEW

File: test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt [hunk 1]
```diff
@@ -17,6 +19,8 @@ import java.nio.file.Paths
 class XctestrunTest {
 
     private val swiftXctestrun = "$fixturesPath/EarlGreyExampleSwiftTests_iphoneos13.4-arm64e.xctestrun"
+    private val multipleTargetsSwiftXctestrun = "$fixturesPath/axel/AllTests_iphoneos13.7-arm64e.xctestrun"
```
Comment (axelzuziak-gogo) [inline test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt:22]: @jan-gogo In order to test new functionality, I have to add some new fixtures, but we should wait for this PR first:
https://github.com/Flank/flank/pull/1148, right?

Comment (jan-gogo) [reply test_runner/src/test/kotlin/ftl/ios/XctestrunTest.kt:22]: > @jan-gogo In order to test new functionality, I have to add some new fixtures, but we should wait for this PR
> #1148, right?

Right

File: .gitignore [hunk 2]
```diff
@@ -9,3 +9,4 @@ test_runner/flank/
 local.properties
 /report.json
 results
+xcuserdata/
```
Comment (axelzuziak-gogo) [inline .gitignore:12]: User generated data for iOS projects (breakpoints, interface state etc.)

File: test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -509,9 +509,9 @@
 				COPY_PHASE_STRIP = NO;
 				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
 				DEFINES_MODULE = NO;
-				DEVELOPMENT_TEAM = AD2V26JBWL;
+				DEVELOPMENT_TEAM = L2UF9MLSM6;
```
Comment (axelzuziak-gogo) [inline test_projects/ios/EarlGreyExample/EarlGreyExample.xcodeproj/project.pbxproj:512]: Using GogoApps code signing

File: test_projects/ios/EarlGreyExample/ops.sh [hunk 4]
```diff
@@ -52,20 +52,27 @@ function earl_grey_example() {
...
 
       cp \
         "$productsDir/Debug-iphoneos/EarlGreyExampleSwift.app/PlugIns/EarlGreyExampleTests.xctest/EarlGreyExampleTests" \
-        "$FLANK_FIXTURES_TMP/objc/"
+        "$FLANK_FIXTURES_TMP/ios/earl_grey_example/objc/"
 
       cp \
         "$productsDir/Debug-iphoneos/EarlGreyExampleSwift.app/PlugIns/EarlGreyExampleSwiftTests.xctest/EarlGreyExampleSwiftTests" \
-        "$FLANK_FIXTURES_TMP/swift/"
+        "$FLANK_FIXTURES_TMP/ios/earl_grey_example/swift/"
```
Comment (axelzuziak-gogo) [inline test_projects/ios/EarlGreyExample/ops.sh:72]: Little cleanup inside tmp directory

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt [hunk 5]
```diff
@@ -69,28 +70,27 @@ private fun IosArgs.calculateShardChunks() = if (disableSharding)
...
+    testTargetsRgx: List<String?>
+): XctestrunMethods =
+    if (testTargetsRgx.isEmpty()) validTestMethods
+    else validTestMethods.mapValues {
+        it.value.filter { test ->
+            testTargetsRgx.filterNotNull().forEach { target ->
+                try {
+                    if (test.matches(target.toRegex())) return@filter true
+                } catch (e: Exception) {
+                    throw FlankConfigurationError("Invalid regex: $target", e)
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/args/IosArgs.kt:91]:
```suggestion
internal fun filterTests(
    validTestMethods: XctestrunMethods,
    testTargetsRgx: List<String>
): XctestrunMethods =
    if (testTargetsRgx.isEmpty()) validTestMethods
    else validTestMethods.mapValues { (_, tests) ->
        tests.filter { test ->
            testTargetsRgx.any { target ->
                try {
                    test.matches(target.toRegex())
                } catch (e: Exception) {
                    throw FlankConfigurationError("Invalid regex: $target", e)
```

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt [hunk 6]
```diff
@@ -69,28 +70,27 @@ private fun IosArgs.calculateShardChunks() = if (disableSharding)
...
                 }
-            } catch (e: Exception) {
-                throw FlankConfigurationError("Invalid regex: $target", e)
             }
+            false
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/args/IosArgs.kt:94]:
```suggestion
```

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 7]
```diff
@@ -70,41 +79,60 @@ object Xctestrun {
...
-        // Test-Class-Name[/Test-Method-Name]
-        // Example/testExample
-        for (testTarget in root.allKeys()) {
-            val testDictionary = (root[testTarget] as NSDictionary)
+    fun findTestNames(testTarget: String, xctestrun: String): List<String> {
+        return findTestNamesForTarget(
+            testTarget = testTarget,
+            xctestrun = File(xctestrun)
+        )
+    }
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:91]:
```suggestion
    fun findTestNames(testTarget: String, xctestrun: String): List<String> =
        findTestNamesForTarget(
            testTarget = testTarget,
            xctestrun = File(xctestrun)
        )
```

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 8]
```diff
@@ -70,41 +79,60 @@ object Xctestrun {
...
+            throw FlankGeneralError("XCTestrun does not contain $testTarget test target.")
         }
+        val testDictionary = (rootDictionary[testTarget] as NSDictionary)
+
+        return testsForTarget(
+            testDictionary = testDictionary,
+            testRoot = testRoot,
+            testTarget = testTarget
+        ).distinct()
+    }
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:117]:
```suggestion
    private fun findTestNamesForTarget(
        testTarget: String, 
        xctestrun: File
    ): List<String> =
        testsForTarget(
            testDictionary = parse(xctestrun)[testTarget]
                as? NSDictionary
                ?: throw FlankGeneralError("XCTestrun does not contain $testTarget test target."),
            testRoot = xctestrun.parent + "/",
            testTarget = testTarget
        ).distinct()
```

File: test_projects/ios/EarlGreyExample/ops.sh (hunk 4 above)
Comment (jan-gogo) [reply test_projects/ios/EarlGreyExample/ops.sh:72]: Make sure this path is also updated in the rest of the project.

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt (hunk 6 above)
Comment (jan-gogo) [reply test_runner/src/main/kotlin/ftl/args/IosArgs.kt:94]: The second part of the suggestion above

File: test_runner/build.gradle.kts [hunk 9]
```diff
@@ -136,7 +136,7 @@ detekt {
     input = files("src/main/kotlin", "src/test/kotlin")
     config = files("../config/detekt.yml")
     parallel = true
-    failFast = true // fail build on any finding
+    failFast = false // fail build on any finding
```
[the remark this answers is not in the document]
Comment (axelzuziak-gogo) [reply test_runner/build.gradle.kts]: Sorry, changed this for testing - already removed

**Comment by pawelpasterz** [comment]
https://github.com/Flank/flank/pull/1219/checks?check_run_id=1273854203#step:5:147

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt [hunk 10]
```diff
@@ -69,28 +70,26 @@ private fun IosArgs.calculateShardChunks() = if (disableSharding)
...
+internal fun filterTests(
+    validTestMethods: XctestrunMethods,
+    testTargetsRgx: List<String>
+): XctestrunMethods =
+    if (testTargetsRgx.isEmpty()) validTestMethods
+    else validTestMethods.mapValues { (_, tests) ->
+        tests.filter { test ->
+            testTargetsRgx.any { target ->
+                try {
+                    test.matches(target.toRegex())
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/args/IosArgs.kt:89]: Let's map `testTargetsRgx` into regex (its name actually indicates to be a list of regex) and reuse it. Current implementation parse all `testTargetsRgx` members for each `validTestMethods` value separately

Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/args/IosArgs.kt:89]: Let's map `testTargetsRgx` into regex (its name actually indicates to be a list of regex) and reuse it. Current implementation parse all `testTargetsRgx` members for each `validTestMethods` value separately

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 11]
```diff
@@ -4,11 +4,20 @@ import com.dd.plist.NSArray
...
+import com.google.common.annotations.VisibleForTesting
 import ftl.run.exception.FlankGeneralError
 import java.io.ByteArrayOutputStream
 import java.io.File
 import java.nio.file.Paths
 
+/*
+{
+  "TestTarget": ["method1", "method2"],
+  "TestTarget2: ["method3", "method4"]
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:16]:
```suggestion
  "TestTarget2": ["method3", "method4"]
```

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 12]
```diff
@@ -70,41 +79,55 @@ object Xctestrun {
...
+            testDictionary = parse(xctestrun)[testTarget]
+                as? NSDictionary
+                ?: throw FlankGeneralError("XCTestrun does not contain $testTarget test target."),
+            testRoot = xctestrun.parent + "/",
+            testTarget = testTarget
+        ).distinct()
+
+    fun rewrite(xctestrun: String, methods: List<String>): ByteArray {
+        val xctestrunFile = File(xctestrun)
+        val methodsToRun = findTestNames(xctestrunFile).mapValues { it.value.filter { methods.contains(it) } }
```
Comment (pawelpasterz) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:116]: Let's add an explicit parameter for one of `it` to avoid shadowing

Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:116]: I suggest suggestions like that ;)
```suggestion
        val methodsToRun = findTestNames(xctestrunFile).mapValues { (_, list) -> list.filter(methods::contains) }
```

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt (hunk 10 above)
Comment (jan-gogo) [reply test_runner/src/main/kotlin/ftl/args/IosArgs.kt:89]: This is a slight optimization and this pull request is big enough. Let's skip this, it could be fixed in the future.

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt (hunk 12 above)
Comment (jan-gogo) [reply test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:116]: This is a slight optimization and this pull request is big enough. Let's skip this, it could be fixed in the future.

File: test_runner/src/main/kotlin/ftl/args/IosArgs.kt (hunk 10 above)
Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/args/IosArgs.kt:89]: It's a good practice and requires small change

Comment (zuziakaxel) [reply test_runner/src/main/kotlin/ftl/args/IosArgs.kt:89]: Got it! Thanks

**Review by jan-gogo — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 13]
```diff
@@ -4,11 +4,20 @@ import com.dd.plist.NSArray
...
 import com.dd.plist.PropertyListParser
+import com.google.common.annotations.VisibleForTesting
 import ftl.run.exception.FlankGeneralError
 import java.io.ByteArrayOutputStream
 import java.io.File
 import java.nio.file.Paths
 
+/*
+{
+  "TestTarget": ["method1", "method2"],
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:15]: comments? if i am correct @jan-gogo we dont want comments like this :)

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 14]
```diff
@@ -70,41 +79,55 @@ object Xctestrun {
...
-                testDictionary = testDictionary,
-                testRoot = testRoot,
-                testTarget = testTarget
+    fun findTestNames(testTarget: String, xctestrun: String): List<String> =
+        findTestNamesForTarget(
+            testTarget = testTarget,
+            xctestrun = File(xctestrun)
+        )
+
+    /* Finds tests in a xctestrun file */
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:92]: same as above

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 15]
```diff
@@ -70,41 +79,55 @@ object Xctestrun {
...
+            testTarget to findTestNamesForTarget(
+                testTarget = testTarget,
+                xctestrun = xctestrun
             )
-
-            result += methods
         }
 
-        return result.distinct()
+    /* Finds tests for testTarget in xctestrun file */
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:101]: same as above

**Review by pawelpasterz — APPROVED** [review]
Just address @Sloox 'es comments and good to go

**Comment by piotradamczyk5** [comment]
> Just address @Sloox 'es comments and good to go

And also please check tests on Windows 😄 
Probably you could skip them for now with TODO comment about solving it in #1134

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt [hunk 16]
```diff
@@ -4,11 +4,20 @@ import com.dd.plist.NSArray
...
 import java.io.ByteArrayOutputStream
 import java.io.File
 import java.nio.file.Paths
 
+/*
+{
+  "TestTarget": ["method1", "method2"],
+  "TestTarget2": ["method3", "method4"]
+}
+*/
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:18]:
```suggestion
```

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt (hunk 14 above)
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:92]:
```suggestion
```

File: test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt (hunk 15 above)
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/ios/Xctestrun.kt:101]:
```suggestion
```

**Review by piotradamczyk5 — APPROVED** [review]

**Review by piotradamczyk5 — CHANGES_REQUESTED** [review]
> Just address @Sloox 'es comments and good to go

And also please check tests on Windows 😄 
Probably you could skip them for now with TODO comment about solving them in #1134
