### PR TITLE
#810 Prints matrix error as table

### LINKED ISSUE #810: Display matrix results in a table format
Current Flank output:
```
Error: Matrix failed: matrix-2kfcwoyh1z9tz FINISHED failure  https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/7897562908617453208
Error: Matrix failed: matrix-4ssc3q1dsjfxa FINISHED failure  https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/6539867209135871024
```

gcloud output:

```
More details are available at [https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.bf178d418be9d33e/matrices/7974756372300129768].
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ Failed  │ walleye-26-en-portrait │ Test failed to run │
└─────────┴────────────────────────┴────────────────────┘
```

Let's add a table display for matrix outcomes that matches gcloud. The gcloud source code is available here: https://github.com/Flank/gcloud_cli

- https://github.com/Flank/gcloud_cli/search?q=TEST_AXIS_VALUE&unscoped_q=TEST_AXIS_VALUE

### PR DESCRIPTION
**Pull request by piotradamczyk5**
Fixes #810 

## Checklist

- [x] Unit tested
- [x] release_notes.md updated

### CODE REVIEW

File: test_runner/src/test/kotlin/ftl/util/UtilsTest.kt [hunk 1]
```diff
@@ -172,11 +169,16 @@ class UtilsTest {
...
+        exit.checkAssertionAfterwards {
+            assertTrue(output.log.contains("1"))
+            assertTrue(output.log.contains("Error: Matrix failed: 2"))
+        }
+
         // when
         withGlobalExceptionHandling(block)
-        // then
-        assertTrue(output.log.contains("Error: Matrix failed: 1"))
-        assertTrue(output.log.contains("Error: Matrix failed: 2"))
```
Comment (piotradamczyk5) [inline test_runner/src/test/kotlin/ftl/util/UtilsTest.kt:179]: this test will be updated cause assert methods was not called after `System.exit`, so I introduced new testing behavior given-will-when 😄 to make them work

File: test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+        tableLines
+            .map { it.length }
+            .zipWithNext()
+            .forEach { (previous, next) ->
+                assert(previous == next)
+            }
+    }
+
+    @Test
+    fun `table first line should contains correct characters`() {
```
Comment (bootstraponline) [inline test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt:31]: What do you think of testing the table against a reference output?


```
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ Failed  │ walleye-26-en-portrait │ Test failed to run │
└─────────┴────────────────────────┴────────────────────┘
```

This seems easier to understand since we're testing the behavior instead of the implementation details.

Comment (piotradamczyk5) [reply test_runner/src/test/kotlin/ftl/util/LogTableBuilderTest.kt:31]: yes I will add comparing with reference table in UtilsTests :)

**Comment by jan-gogo** [comment]
I wonder if #810 is about displaying only error outputs or maybe also successed. @bootstraponline ?

**Comment by bootstraponline** [comment]
> I wonder if #810 is about displaying only error outputs or maybe also successed. @bootstraponline ?

I think we should display the results (failed, success, etc.) for each matrix. Same as gcloud CLI.

**Comment by piotradamczyk5** [comment]
> Add support for other status types

I have added printing `MatrixResultsReport` as table

File: test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt [hunk 3]
```diff
@@ -0,0 +1,27 @@
+package ftl.util
+
+import ftl.json.SavedMatrix
+
+fun SavedMatrix.asPrintableTable(): String {
+    return buildTable(
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt:6]: maybe `list(this).asPrintableTable()`?

File: test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+        TableColumn(OUTCOME_COLUMN_HEADER, listOf(outcome), OUTCOME_COLUMN_SIZE),
+        TableColumn(MATRIX_ID_COLUMN_HEADER, listOf(matrixId), MATRIX_ID_COLUMN_SIZE),
+        TableColumn(OUTCOME_DETAILS_COLUMN_HEADER, listOf(outcomeDetails), OUTCOME_DETAILS_COLUMN_SIZE)
+    )
+}
+
+fun List<SavedMatrix>.asPrintableTable(): String {
+
+    return buildTable(
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt:15]: could be expression

File: test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt [hunk 5]
```diff
@@ -29,16 +29,9 @@ object MatrixResultsReport : IReport {
...
-            total += 1
-
-            // unfinished matrix will not be reported as failed since it's still running
-            if (matrix.failed().not()) {
-                success += 1
-            }
-        }
+        val total = matrices.map.size
+        // unfinished matrix will not be reported as failed since it's still running
+        val success = matrices.map.values.count { it.failed().not() }
```
Comment (jan-gogo) [inline test_runner/src/main/kotlin/ftl/reports/MatrixResultsReport.kt:34]: 👍

**Comment by jan-gogo** [comment]
For Debug.kt
```
    val quantity = "single"
    val type = "error"
```
Table is printed twice

```
AndroidArgs
    gcloud:
      results-bucket: test-lab-v9cn46bb990nx-kz69ymd4nm9aq
      results-dir: null
      record-video: false
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: /Users/janek/projects/flank-project/flank-review/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
      test: /Users/janek/projects/flank-project/flank-review/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-error-debug-androidTest.apk
      additional-apks: 
      auto-google-login: false
      use-orchestrator: true
      directories-to-pull:
        - /sdcard/
      other-files:
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
      robo-directives:
      robo-script: null
      device:
        - model: NexusLowRes
          version: 28
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0

    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      files-to-download:
        - .*/sdcard/[^/]+\.ec$
      test-targets-always-run:
      disable-sharding: true
      project: flank-open-source
      local-result-dir: results
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
      output-style: verbose

RunTests
  Uploading app-debug.apk   Uploading app-single-error-debug-androidTest.apk ..

  1 test / 1 shard

  1 matrix ids created in 0m 6s
  https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-29_12-06-17.849000_lOtW

Matrices webLink
  matrix-23ywqaa9yt86m https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8785051465867885324/executions/bs.f52b9341ebd2e7de

  0m  1s matrix-23ywqaa9yt86m NexusLowRes-28 PENDING
  0m 31s matrix-23ywqaa9yt86m NexusLowRes-28 Starting attempt 1.
  0m 31s matrix-23ywqaa9yt86m NexusLowRes-28 RUNNING
  1m 32s matrix-23ywqaa9yt86m NexusLowRes-28 Started logcat recording.
  1m 32s matrix-23ywqaa9yt86m NexusLowRes-28 Preparing device.
  1m 57s matrix-23ywqaa9yt86m NexusLowRes-28 Installing apps.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Pre-Test Package Stats information from the device.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Performance Environment information from the device.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Started crash detection.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Started crash monitoring.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Starting instrumentation test.
  2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Completed instrumentation test.
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Stopped crash monitoring.
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Post-test Package Stats information from the device.
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Stopped logcat recording.
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Done. Test time = 6 (secs)
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Starting results processing. Attempt: 1
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Completed results processing. Time taken = 2 (secs)
  2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 FINISHED
  2m 33s matrix-23ywqaa9yt86m FINISHED

FetchArtifacts
  .
  Updating matrix file

CostReport
  Virtual devices
    $0.02 for 1m

MatrixResultsReport
  0 / 1 (0.00%)
  1 matrices failed

┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ failure │  matrix-23ywqaa9yt86m  │                    │
└─────────┴────────────────────────┴────────────────────┘
More details are available at [https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8785051465867885324/executions/bs.f52b9341ebd2e7de]
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ failure │  matrix-23ywqaa9yt86m  │                    │
└─────────┴────────────────────────┴────────────────────┘

Process finished with exit code 1
```

**Comment by piotradamczyk5** [comment]
> For Debug.kt
> 
> ```
>     val quantity = "single"
>     val type = "error"
> ```
> 
> Table is printed twice
> 
> ```
> AndroidArgs
>     gcloud:
>       results-bucket: test-lab-v9cn46bb990nx-kz69ymd4nm9aq
>       results-dir: null
>       record-video: false
>       timeout: 15m
>       async: false
>       client-details: 
>       network-profile: null
>       results-history-name: null
>       # Android gcloud
>       app: /Users/janek/projects/flank-project/flank-review/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-debug.apk
>       test: /Users/janek/projects/flank-project/flank-review/test_runner/src/test/kotlin/ftl/fixtures/tmp/apk/app-single-error-debug-androidTest.apk
>       additional-apks: 
>       auto-google-login: false
>       use-orchestrator: true
>       directories-to-pull:
>         - /sdcard/
>       other-files:
>       performance-metrics: false
>       num-uniform-shards: null
>       test-runner-class: null
>       test-targets:
>       robo-directives:
>       robo-script: null
>       device:
>         - model: NexusLowRes
>           version: 28
>           locale: en
>           orientation: portrait
>       num-flaky-test-attempts: 0
> 
>     flank:
>       max-test-shards: 1
>       shard-time: -1
>       num-test-runs: 1
>       smart-flank-gcs-path: 
>       smart-flank-disable-upload: false
>       files-to-download:
>         - .*/sdcard/[^/]+\.ec$
>       test-targets-always-run:
>       disable-sharding: true
>       project: flank-open-source
>       local-result-dir: results
>       # Android Flank Yml
>       keep-file-path: false
>       additional-app-test-apks:
>       run-timeout: -1
>       legacy-junit-result: false
>       ignore-failed-tests: false
>       output-style: verbose
> 
> RunTests
>   Uploading app-debug.apk   Uploading app-single-error-debug-androidTest.apk ..
> 
>   1 test / 1 shard
> 
>   1 matrix ids created in 0m 6s
>   https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-29_12-06-17.849000_lOtW
> 
> Matrices webLink
>   matrix-23ywqaa9yt86m https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8785051465867885324/executions/bs.f52b9341ebd2e7de
> 
>   0m  1s matrix-23ywqaa9yt86m NexusLowRes-28 PENDING
>   0m 31s matrix-23ywqaa9yt86m NexusLowRes-28 Starting attempt 1.
>   0m 31s matrix-23ywqaa9yt86m NexusLowRes-28 RUNNING
>   1m 32s matrix-23ywqaa9yt86m NexusLowRes-28 Started logcat recording.
>   1m 32s matrix-23ywqaa9yt86m NexusLowRes-28 Preparing device.
>   1m 57s matrix-23ywqaa9yt86m NexusLowRes-28 Installing apps.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Pre-Test Package Stats information from the device.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Performance Environment information from the device.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Started crash detection.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Started crash monitoring.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Starting instrumentation test.
>   2m  3s matrix-23ywqaa9yt86m NexusLowRes-28 Completed instrumentation test.
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Stopped crash monitoring.
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Retrieving Post-test Package Stats information from the device.
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Stopped logcat recording.
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Done. Test time = 6 (secs)
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Starting results processing. Attempt: 1
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 Completed results processing. Time taken = 2 (secs)
>   2m 33s matrix-23ywqaa9yt86m NexusLowRes-28 FINISHED
>   2m 33s matrix-23ywqaa9yt86m FINISHED
> 
> FetchArtifacts
>   .
>   Updating matrix file
> 
> CostReport
>   Virtual devices
>     $0.02 for 1m
> 
> MatrixResultsReport
>   0 / 1 (0.00%)
>   1 matrices failed
> 
> ┌─────────┬────────────────────────┬────────────────────┐
> │ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
> ├─────────┼────────────────────────┼────────────────────┤
> │ failure │  matrix-23ywqaa9yt86m  │                    │
> └─────────┴────────────────────────┴────────────────────┘
> More details are available at [https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8785051465867885324/executions/bs.f52b9341ebd2e7de]
> ┌─────────┬────────────────────────┬────────────────────┐
> │ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
> ├─────────┼────────────────────────┼────────────────────┤
> │ failure │  matrix-23ywqaa9yt86m  │                    │
> └─────────┴────────────────────────┴────────────────────┘
> 
> Process finished with exit code 1
> ```

Basically the first table is  a summary report for all matrix (if you have many matrices, it will print them all) and second one log error of each matrix.

To fix this issue I could skip printing table as error log in `Utils.kt#withGlobalExceptionHandling ` this is much decision about how output should look like.

File: test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt (hunk 4 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt]: changed

File: test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt (hunk 3 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/util/SavedMatrixTableUtil.kt]: changed

**Comment by bootstraponline** [comment]
> Basically the first table is a summary report for all matrix (if you have many matrices, it will print them all) and second one log error of each matrix.
> 
> To fix this issue I could skip printing table as error log in `Utils.kt#withGlobalExceptionHandling ` this is much decision about how output should look like.

I'd study the gcloud CLI matrix table. We should be able to port that to Kotlin.
https://github.com/Flank/gcloud_cli/search?q=TEST_AXIS_VALUE&unscoped_q=TEST_AXIS_VALUE

The end result should be only one table. Primarily the goal of Flank is to match gcloud, and add a bit of extra features on top. 🙂

**Comment by bootstraponline** [comment]
Here's one way you can test the PR:

Run `flank.yml` with Flank.
- `flank android run`

Run the same `flank.yml` with gcloud. The table output should match. 🙂 
- `gcloud firebase test android run flank.yml:gcloud`

**Comment by piotradamczyk5** [comment]
I made output table same as for GCloud ( link, single table, status color etc)
I used `outcomeDetails` to print `TEST_DETAILS`, but it is usually empty. Should I used other data to print test details? Outcome details in my opinion is good for it

**Comment by adamfilipow92** [comment]
I will check outputs
Flank table:
```
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ failure │  matrix-d587bp9k4fcda  │                    │
└─────────┴────────────────────────┴────────────────────┘

```

and Test Lab

```
┌─────────┬────────────────────────┬─────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │     TEST_DETAILS    │
├─────────┼────────────────────────┼─────────────────────┤
│ Failed  │ walleye-26-en-portrait │ 1 test cases failed │
└─────────┴────────────────────────┴─────────────────────┘

```
Colors are the same. But in flank we don't have TEST_DETAILS filled. I don't known its ok so please tell what you think. @bootstraponline @pawelpasterz @jan-gogo

**Comment by piotradamczyk5** [comment]
> I will check outputs
> Flank table:
> 
> ```
> ┌─────────┬────────────────────────┬────────────────────┐
> │ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
> ├─────────┼────────────────────────┼────────────────────┤
> │ failure │  matrix-d587bp9k4fcda  │                    │
> └─────────┴────────────────────────┴────────────────────┘
> ```
> 
> and Test Lab
> 
> ```
> ┌─────────┬────────────────────────┬─────────────────────┐
> │ OUTCOME │    TEST_AXIS_VALUE     │     TEST_DETAILS    │
> ├─────────┼────────────────────────┼─────────────────────┤
> │ Failed  │ walleye-26-en-portrait │ 1 test cases failed │
> └─────────┴────────────────────────┴─────────────────────┘
> ```
> 
> Colors are the same. But in flank we don't have TEST_DETAILS filled. I don't known its ok so please tell what you think. @bootstraponline @pawelpasterz @jan-gogo

Yes, that's the question which I asked above about properly data usage

**Comment by pawelpasterz** [comment]
> > I will check outputs
> > Flank table:
> > ```
> > ┌─────────┬────────────────────────┬────────────────────┐
> > │ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
> > ├─────────┼────────────────────────┼────────────────────┤
> > │ failure │  matrix-d587bp9k4fcda  │                    │
> > └─────────┴────────────────────────┴────────────────────┘
> > ```
> > 
> > 
> > and Test Lab
> > ```
> > ┌─────────┬────────────────────────┬─────────────────────┐
> > │ OUTCOME │    TEST_AXIS_VALUE     │     TEST_DETAILS    │
> > ├─────────┼────────────────────────┼─────────────────────┤
> > │ Failed  │ walleye-26-en-portrait │ 1 test cases failed │
> > └─────────┴────────────────────────┴─────────────────────┘
> > ```
> > 
> > 
> > Colors are the same. But in flank we don't have TEST_DETAILS filled. I don't known its ok so please tell what you think. @bootstraponline @pawelpasterz @jan-gogo
> 
> Yes, that's the question which I asked above about properly data usage
> 
> > I made output table same as for GCloud ( link, single table, status color etc)
> > I used `outcomeDetails` to print `TEST_DETAILS`, but it is usually empty. Should I use other data to print test details? Outcome details in my opinion should be good for it

IMO we should try to fix it but in separate issue/PR. If we want to reflect gcloud results I think there would be some refactor needed
https://github.com/Flank/gcloud_cli/blob/cca7556cc832be02b3523c0fe86fdbdcd33078c4/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/results_summary.py#L326

**Comment by piotradamczyk5** [comment]
> > > I will check outputs
> > > Flank table:
> > > ```
> > > ┌─────────┬────────────────────────┬────────────────────┐
> > > │ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
> > > ├─────────┼────────────────────────┼────────────────────┤
> > > │ failure │  matrix-d587bp9k4fcda  │                    │
> > > └─────────┴────────────────────────┴────────────────────┘
> > > ```
> > > 
> > > 
> > > and Test Lab
> > > ```
> > > ┌─────────┬────────────────────────┬─────────────────────┐
> > > │ OUTCOME │    TEST_AXIS_VALUE     │     TEST_DETAILS    │
> > > ├─────────┼────────────────────────┼─────────────────────┤
> > > │ Failed  │ walleye-26-en-portrait │ 1 test cases failed │
> > > └─────────┴────────────────────────┴─────────────────────┘
> > > ```
> > > 
> > > 
> > > Colors are the same. But in flank we don't have TEST_DETAILS filled. I don't known its ok so please tell what you think. @bootstraponline @pawelpasterz @jan-gogo
> > 
> > 
> > Yes, that's the question which I asked above about properly data usage
> > > I made output table same as for GCloud ( link, single table, status color etc)
> > > I used `outcomeDetails` to print `TEST_DETAILS`, but it is usually empty. Should I use other data to print test details? Outcome details in my opinion should be good for it
> 
> @adamfilipow92
> IMO we should try to fix it but in separate issue/PR. If we want to reflect gcloud results I think there would be some refactor needed (small PR scope principle)
> https://github.com/Flank/gcloud_cli/blob/cca7556cc832be02b3523c0fe86fdbdcd33078c4/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/results_summary.py#L326

Should I create a task for it?

**Comment by jan-gogo** [comment]
>IMO we should try to fix it but in separate issue/PR. If we want to reflect gcloud results I think there would be some refactor needed (small PR scope principle)

I guess It's a good idea If you feel more comfortable with separated issue/PR

**Comment by piotradamczyk5** [comment]
> @piotradamczyk5
> 
> > IMO we should try to fix it but in separate issue/PR. If we want to reflect gcloud results I think there would be some refactor needed (small PR scope principle)
> 
> I guess It's a good idea If you feel more comfortable with separated issue/PR

Created https://github.com/Flank/flank/issues/829

**Comment by bootstraponline** [comment]
I agree, let's match gcloud output. Having this as a new task makes sense. https://github.com/Flank/flank/issues/829 🙂
