### PR TITLE
fix: Reflect gclouds outcome for robo tests

### LINKED ISSUE #1120: Reflect gcloud output for robo tests
**Describe the bug**
> A clear and concise description of what the bug is.

Flank is printing inaccurate output (mixed with one for instrumentation tests). See screenshots below (test details and shard info)
##### flank:
Screenshot 2020-09-14 at 09 09 24
Screenshot 2020-09-14 at 09 09 32

##### gcloud:
Screenshot 2020-09-14 at 09 16 13

**To Reproduce**
> Steps to reproduce the behavior:

1. Run any robo test

**Expected behavior**
> A clear and concise description of what you expected to happen.

`flank` should reflects `gcloud`'s output

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>

 yes 

> Post the output of ` flank --version`.

```
version: local_snapshot
revision: bd20cb452aee9ca1625891598a66dcf27e1767d7
```

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #1120 

Flank should reflect gcloud's output for robo tests:
Screenshot 2020-09-15 at 13 01 44
Screenshot 2020-09-15 at 18 42 30
Screenshot 2020-09-15 at 18 42 43

Use this [SCRIPT](https://gist.github.com/pawelpasterz/cb0bdab77fc92ba8d83d3394faee3002) to simulate failing robo

All other functionalities related to running tests remain the same

## Checklist

- [x] Unit tested

### CODE REVIEW

**Review by Sloox — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt [hunk 1]
```diff
@@ -14,9 +14,11 @@ import ftl.util.StepOutcome.success
...
 internal fun Outcome?.getDetails(
-    testSuiteOverviewData: TestSuiteOverviewData?
+    testSuiteOverviewData: TestSuiteOverviewData?,
+    isRoboTest: Boolean = false
 ): String = when (this?.summary) {
-    success, flaky -> testSuiteOverviewData
+    success, flaky -> if (isRoboTest) "---"
+    else testSuiteOverviewData
         ?.getSuccessOutcomeDetails(successDetail?.otherNativeCrash ?: false)
         ?: "Unknown outcome"
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt:23]: could you move 
```kotlin
testSuiteOverviewData
        ?.getSuccessOutcomeDetails(successDetail?.otherNativeCrash ?: false)
        ?: "Unknown outcome"
```
to separate method and make single line
```kotlin
success, flaky -> if (isRoboTest) "---" else newMethod()
```

for better readability ?

File: test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt [hunk 2]
```diff
@@ -2,15 +2,14 @@ package ftl.reports.outcome
...
-        }
+fun TestOutcomeContext.createMatrixOutcomeSummary() = Pair(
+    steps.calculateAndroidBillableMinutes(projectId, testTimeout),
+    if (environments.hasOutcome())
+        createMatrixOutcomeSummaryUsingEnvironments()
+    else {
+        if (steps.isEmpty()) println("No test results found, something went wrong. Try re-running the tests.")
+        createMatrixOutcomeSummaryUsingSteps()
+    }
+)
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt:13]: for consistency
```suggestion

    steps.calculateAndroidBillableMinutes(projectId, testTimeout) to
    if (environments.hasOutcome())
        createMatrixOutcomeSummaryUsingEnvironments()
    else {
        if (steps.isEmpty()) println("No test results found, something went wrong. Try re-running the tests.")
        createMatrixOutcomeSummaryUsingSteps()
    }

```

File: test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt (hunk 1 above)
Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/json/OutcomeDetailsFormatter.kt:23]: Like your proposal, thanks for catching this!

File: test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt (hunk 2 above)
Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt:13]: Yeah, I changed to `Pair(...)` because leads to nasty indention
```kotlin
steps.calculateAndroidBillableMinutes(projectId, testTimeout) to
            if (environments.hasOutcome())
                createMatrixOutcomeSummaryUsingEnvironments()
            else {
                if (steps.isEmpty()) println("No test results found, something went wrong. Try re-running the tests.")
                createMatrixOutcomeSummaryUsingSteps()
            }
```
And IMHO it's less readable. `if` looks like it is chained, `to` is very easy to omitted.
I don't have a strong opinion regarding this and sure I can change it if you prefer that way :)

Comment (pawelpasterz) [reply test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt]: On the second thought, I decided to refactor this, even more, please check latest implementation

**Comment by pawelpasterz** [comment]
@Mergifyio refresh

**Review by piotradamczyk5 — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt (hunk 2 above)
Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/reports/outcome/CreateMatrixOutcomeSummary.kt]: like it!
