### PR TITLE
fix: Add additional index to matrix when multiple test runs

### LINKED ISSUE #1258: Multiple test runs overwrite artifacts stored in GCS
Args:
```
version: v20.08.1

--
revision: e9ed26c8f2fdc77fca9f0e436558d89f7f99ef17  

AndroidArgs
    gcloud:
        results-bucket: test-lab-vw4y21tcm9700-i1dn5xsbfdmaq
        results-dir: 2020-10-20_18-30-16.560000_jQtn
        record-video: true
        timeout: 5m
        async: false
        client-details:
        network-profile: null
        results-history-name: null
        # Android gcloud
        app: app.apk
        test: test.apk
        additional-apks:
        auto-google-login: false
        use-orchestrator: true
        directories-to-pull:
        other-files:
        performance-metrics: true
        num-uniform-shards: null
        test-runner-class: null
        test-targets:
        - class *
        robo-directives:
        robo-script: null
        device:
        - model: NexusLowRes
        version: 28
        locale: en
        orientation: portrait
        num-flaky-test-attempts: 0
     
    flank:
        max-test-shards: 200
        shard-time: -1
        num-test-runs: 2
        smart-flank-gcs-path:
        smart-flank-disable-upload: false
        files-to-download:
        test-targets-always-run:
        disable-sharding: false
        project: test-lab-test-project
        local-result-dir: */results
        full-junit-result: false
        # Android Flank Yml
        keep-file-path: false
        additional-app-test-apks:
        run-timeout: -1
        legacy-junit-result: false
        ignore-failed-tests: false
        output-style: single
```

`matrix_ids.json`
```
{
  "matrix-1xu48uuiz8s8a": {
    "matrixId": "matrix-1xu48uuiz8s8a",
    "state": "FINISHED",
    "gcsPath": "test-lab-vw4y21tcm9700-i1dn5xsbfdmaq/2020-10-20_18-30-16.560000_jQtn/matrix_0/",
    "webLink": "https://console.firebase.google.com/project/test-lab-test-project/testlab/histories/bh.bc577d7d68c5df5b/matrices/7166322024737888455/executions/bs.3f5af246467cbad5",
    "downloaded": true,
    "billableVirtualMinutes": 2,
    "billablePhysicalMinutes": 0,
    "outcome": "success",
    "outcomeDetails": "1 test cases passed"
  },
  "matrix-13qyttauzisfy": {
    "matrixId": "matrix-13qyttauzisfy",
    "state": "FINISHED",
    "gcsPath": "test-lab-vw4y21tcm9700-i1dn5xsbfdmaq/2020-10-20_18-30-16.560000_jQtn/matrix_0/",
    "webLink": "https://console.firebase.google.com/project/test-lab-test-project/testlab/histories/bh.bc577d7d68c5df5b/matrices/7939366739929940182/executions/bs.72029014ef90ed5f",
    "downloaded": true,
    "billableVirtualMinutes": 2,
    "billablePhysicalMinutes": 0,
    "outcome": "success",
    "outcomeDetails": "1 test cases passed"
  }
}
```

See conflicting gcsPath in both matrices. Artifacts are overwritten between the two. GCS paths should be different to avoid overwriting.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1258 

1. When ```num-test-runs``` set Flank should add to the matrix directory name ```_$index``` on end.
2. When ```num-test-runs``` not set directory name shouldn't contain an additional index.

### CODE REVIEW

**Comment by adamfilipow92** [comment]
After a call with @pawelpasterz, we want to add some tests, so I convert it to draft

File: test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt [hunk 1]
```diff
@@ -78,6 +78,10 @@ internal suspend fun runAndroidTests(args: AndroidArgs): TestResult = coroutineS
     )
 }
 
+private fun String.createGcsPath(contextIndex: Int, runIndex: Int) =
+    if (runIndex == 0) "$this/matrix_$contextIndex/"
+    else "$this/matrix_${contextIndex}_$runIndex/"
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt:83]:
```suggestion
    else "$this/matrix_$contextIndex_$runIndex/"
```

**Review by Sloox — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt (hunk 1 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt:83]: Without put ```contextIndex``` in ```{ }``` IntelliJ thinks ```_``` is a part of value name, so build is failing. 😄

**Review by piotradamczyk5 — APPROVED** [review]
