### PR TITLE
Run *list commands when flank.yml not found should display right output 

### LINKED ISSUE #925: locales, models, test-environment not working without config file.
**Describe the bug**
> A clear and concise description of what the bug is.
When the user runs flank with command `flank android models list`, a message `File not found: ./flank.yml` is displayed. 
`gcloud` config file is not used as a fallback source of settings.

**To Reproduce**
> Steps to reproduce the behavior:

1. Create a new, empty directory
2. Run `flank android models list`* inside newly created dir.
3. `File not found: ./flank.yml`

*the same is for `locales`, `test-environment`

**Expected behavior**
> A clear and concise description of what you expected to happen.
Users should have a table of models displayed.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

version: local_snapshot
revision: 052cd87597876fe01e7ec5171118dbdc776777c7

**Additional context**
> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #925 

Try run flank commands for

```
models
orientations
locales
test-environment
network

```

, without flank.yml this should display lists instead of ```flank.yml``` not found

## Checklist

- [X] Unit tested
- [X] release_notes.md updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/args/AndroidArgsCompanion.kt [hunk 1]
```diff
@@ -24,12 +25,16 @@ open class AndroidArgsCompanion : IArgs.ICompanion {
...
-        createAndroidArgs(defaultAndroidConfig())
+    fun loadOrDefault(yamlPath: Path, cli: AndroidRunCommand? = null) =
+        if (Files.exists(yamlPath)) load(yamlPath, cli)
+        else default()
 
     fun load(yamlPath: Path, cli: AndroidRunCommand? = null) =
         load(loadFile(yamlPath), cli)
 
+    fun default() =
+        createAndroidArgs(defaultAndroidConfig())
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/args/AndroidArgsCompanion.kt:36]: could be single line

File: test_runner/src/main/kotlin/ftl/args/IosArgsCompanion.kt [hunk 2]
```diff
@@ -24,12 +25,16 @@ open class IosArgsCompanion : IArgs.ICompanion {
...
-        createIosArgs(defaultIosConfig())
+    fun loadOrDefault(yamlPath: Path, cli: IosRunCommand? = null) =
+        if (Files.exists(yamlPath)) load(yamlPath, cli)
+        else default()
 
     fun load(yamlPath: Path, cli: IosRunCommand? = null) =
         load(loadFile(yamlPath), cli)
 
+    fun default() =
+        createIosArgs(defaultIosConfig())
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/args/IosArgsCompanion.kt:36]: same here

File: test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt [hunk 3]
```diff
@@ -19,7 +19,7 @@ import java.nio.file.Paths
 )
 class AndroidLocalesListCommand : Runnable {
     override fun run() {
-        println(AndroidCatalog.localesAsTable(projectId = AndroidArgs.load(Paths.get(configPath)).project))
+        println(AndroidCatalog.localesAsTable(projectId = AndroidArgs.loadOrDefault(Paths.get(configPath)).project))
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt:22]: I do not agree with this solution.
We should load config, 
if not present, we should read `System.getenv("GOOGLE_CLOUD_PROJECT") `and 
else we could load default config.

Do you agree with me?

File: test_runner/docs/ascii/flank.jar_-ios-run.adoc [hunk 4]
```diff
@@ -146,15 +146,15 @@ Configuration is read from flank.yml
...
-
 *--xctestrun-file*=_<xctestrunFile>_::
   The path to an .xctestrun file that will override any .xctestrun file contained in the --test package. Because the .xctestrun file contains environment variables along with test methods to run and/or ignore, this can be useful for customizing or sharding test suites. The given path may be in the local filesystem or in Google Cloud Storage using a URL beginning with gs://.
 
 *--xcode-version*=_<xcodeVersion>_::
   The version of Xcode that should be used to run an XCTest. Defaults to the latest Xcode version supported in Firebase Test Lab. This Xcode version must be supported by all iOS versions selected in the test matrix.
 
+*--test*=_<test>_::
+  The path to the test package (a zip file containing the iOS app and XCTest files). The given path may be in the local filesystem or in Google Cloud Storage using a URL beginning with gs://. Note: any .xctestrun file in this zip file will be ignored if --xctestrun-file is specified.
```
Comment (Sloox) [inline test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: Just to make sure, all theses small changes are from the auto doc generation?

File: test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt [hunk 5]
```diff
@@ -18,8 +18,8 @@ private fun createIosArgs(
     commonArgs: CommonArgs
 ) = IosArgs(
     commonArgs = commonArgs.copy(maxTestShards = convertToShardCount(commonArgs.maxTestShards)),
-    xctestrunZip = gcloud.test!!.processFilePath("from test"),
-    xctestrunFile = gcloud.xctestrunFile!!.processFilePath("from xctestrun-file"),
+    xctestrunZip = gcloud.test?.processFilePath("from test").orEmpty(),
```
Comment (Sloox) [inline test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt:21]: is it team or personal preference to us isEmpty() over ?: ""

File: test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt (hunk 3 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt:22]: I think we loading in default config project_id from variable  
Check
```
CommonFlankConfig.default()
```
We use it on generating default configs
and in this function we have used: 
``` 
project = ArgsHelper.getDefaultProjectId() ?: ""

```
getDefaultProjectId() use 
```

ServiceOptions.getDefaultProjectId()

```

this function trying to load from System.getenv("GOOGLE_CLOUD_PROJECT")

Comment (piotradamczyk5) [reply test_runner/src/main/kotlin/ftl/cli/firebase/test/android/configuration/AndroidLocalesListCommand.kt:22]: ok sorry I did not see it 👍

File: test_runner/docs/ascii/flank.jar_-ios-run.adoc (hunk 4 above)
Comment (piotradamczyk5) [reply test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: yeah, they generate different output for same data 😞

Comment (adamfilipow92) [reply test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: Yes, on every build, we have generated docs with changes like that.

File: test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt (hunk 5 above)
Comment (adamfilipow92) [reply test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt:21]: If I right remember we don't have any team preference on it but the implementation of ```orEmpty()``` is
```

/** Returns the string if it is not `null`, or the empty string otherwise. */
@kotlin.internal.InlineOnly
public inline fun String?.orEmpty(): String = this ?: ""

``` 

in cases when we have something more after check ``` .orEmpty() ``` looks better 

```

(ArgsHelper.getDefaultProjectId() ?: "").validOrFail()

```

vs

```

ArgsHelper.getDefaultProjectId().orEmpty().validOrFail()

```

WDYT?

File: test_runner/docs/ascii/flank.jar_-ios-run.adoc (hunk 4 above)
Comment (bootstraponline) [reply test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: I think we should disable the doc generation by default until this is fixed.

@Sloox do you want to handle this contribution?

I think you just have to comment out

https://github.com/Flank/flank/blob/5ea15cf881b1022c74861e618c59e8ac63386501/test_runner/build.gradle.kts#L284-L286

Comment (Sloox) [reply test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: @bootstraponline Sure. is there an issue surrounding this so i can tag the branch correctly? or is a simple "Disable doc generation" sufficent?

Comment (bootstraponline) [reply test_runner/docs/ascii/flank.jar_-ios-run.adoc:156]: this is small enough that we don't need an issue 🙂 "Disable doc generation" sounds great!

File: test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt (hunk 5 above)
Comment (Sloox) [reply test_runner/src/main/kotlin/ftl/args/CreateIosArgs.kt:21]: I am personally more used to ?: but the VS  and use case shows a good use where it definitely looks cleaner and more reasonable to read. Thanks.
