### PR TITLE
fix: set correct max test shards when arm devices are configured

### LINKED ISSUE #2401: maximum `max-test-shards` incorrect for arm virtual devices
**Describe the bug**
When selecting `max-test-shards` of `-1`, flank sets `500` for all virtual devices. According to test lab rest documentation when using arm virtual devices the limit is actually `100`
https://firebase.google.com/docs/test-lab/reference/testing/rest/v1/projects.testMatrices#uniformsharding

I presume this is function which would need to be changed, but I'm not too familiar with the flank codebase.
https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/args/PrepareAndroidCommonConfig.kt#L24

**To Reproduce**
1. Set `max-test-shards` to `-1`
2. Set device config to:
```yml
device:
        - model: SmallPhone.arm
          version: 30
          locale: en
          orientation: portrait
```
3. Observe the outputted config shows:
```yml
max-test-shards: 500
```

**Expected behavior**
I expect flank to determine that arm devices are present and therefore select `100` as the `max-test-shards`.

**Details (please complete the following information):**
version: v23.06.2
revision: c7bd980f44c7be9b179ba93c39d9f487d7b100c7

**Additional context**
None

### PR DESCRIPTION
**Pull request by adamvduke**
Current correct behavior:
* If max-test-shards is set to `-1`, **AND ONLY** physical devices are configured, Flank will adjust max-test-shards to the upper limit for physical devices
* If max-test-shards is set to `-1`, **AND ONLY** virtual devices are configured, Flank will adjust max-test-shards to the upper limit for virtual devices
* If max-test-shards is set to a value higher than the upper limit for physical devices **AND ONLY** physical devices are configured, Flank will throw a configuration error
* If max-test-shards is set to a value higher than the upper limit for physical devices **AND BOTH** physical and virtual devices are configured, Flank will adjust max-test-shards to the upper limit for physical devices
* If max-test-shards is set to a value higher than the upper limit for virtual devices, Flank will throw a configuration error

Current incorrect behavior:
* If max-test-shards is set to `-1`, and ARM devices are configured, Flank will adjust max-test-shards to the upper limit for virtual devices, which is currently higher than the documented upper limit for ARM devices
* If max-test-shards is set to a value higher than the upper limit for ARM devices and ARM devices are configured, Flank will adjust max-test-shards to the upper limit for virtual devices, which is currently higher than the documented upper limit for ARM devices

New behavior:
* If max-test-shards is set to `-1`, and ARM devices are configured, Flank will adjust max-test-shards to the upper limit for ARM devices
* If max-test-shards is set to a value higher than the upper limit for ARM devices **AND ONLY** ARM devices are configured, Flank will throw a configuration error
* If max-test-shards is set to a value higher than the upper limit for ARM devices **AND BOTH** ARM and non-ARM devices are configured, Flank will adjust max-test-shards to the upper limit for ARM devices

Fixes #2401

- [ ] Documented
- [X] Unit tested
- [ ] Integration tests updated

### CODE REVIEW

File: test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt [hunk 1]
```diff
@@ -171,17 +172,23 @@ private fun AndroidArgs.assertMaxTestShardsByDeviceType() =
...
+    when {
+        inVirtualRange && !inPhysicalRange -> logLn("Physical devices configured, but max-test-shards limit set to $maxTestShards. For physical devices range is ${IArgs.AVAILABLE_PHYSICAL_SHARD_COUNT_RANGE.first} to ${IArgs.AVAILABLE_PHYSICAL_SHARD_COUNT_RANGE.last}, you additionally have configured virtual devices. In this case, the maximum shards will be decreased to: ${IArgs.AVAILABLE_PHYSICAL_SHARD_COUNT_RANGE.last}")
+        !inVirtualRange && !inPhysicalRange -> throwMaxTestShardsLimitExceeded()
+    }
 }
 
 private fun AndroidArgs.assertVirtualDevicesShards() {
-    if (!inVirtualRange) throwMaxTestShardsLimitExceeded()
+    when {
+        devices.containsARMDevices() && !devices.containsARMDevices() -> logLn("ARM devices configured, but max-test-shards limit set to $maxTestShards. For ARM devices, the range is ${IArgs.AVAILABLE_VIRTUAL_ARM_SHARD_COUNT_RANGE.first} to ${IArgs.AVAILABLE_VIRTUAL_ARM_SHARD_COUNT_RANGE.last}, you additionally have configured other virtual devices. In this case, the maximum shards will be decreased to: ${IArgs.AVAILABLE_VIRTUAL_ARM_SHARD_COUNT_RANGE.last}")
```
Comment (tonybaroneee) [inline test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt:183]: Is this the right conditional? This appears to always be false?

**Review by tonybaroneee — CHANGES_REQUESTED** [review]
Nice! nit: "ARM" -> "Arm"

File: test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt (hunk 1 above)
Comment (adamvduke) [reply test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt]: updated

**Comment by adamvduke** [comment]
@flank-it

**Review by tonybaroneee — APPROVED** [review]
