### PR TITLE
fix: xArgs command update

### LINKED ISSUE #1538: Flank fails on scanning .xctest for iOS test names
**Describe the bug**
> A clear and concise description of what the bug is.

Running flank on Xcode 12 / bitrise causing Flank Error.
Flank fails on searching test names in a .xctest.

**To Reproduce**
> Steps to reproduce the behavior:

Xcode 12 and bitrise

1. Run 'flank ios run'
2. See error

```
RunTests
Found xctest: /Users/vagrant/deploy/Debug-iphoneos/UITests-Runner.app/PlugIns/UITests.xctest
isMacOS = true (mac os x)
nm -U “/Users/vagrant/deploy/Debug-iphoneos/UITests-Runner.app/PlugIns/UITests.xctest/UITests”
nm -gU “/Users/vagrant/deploy/Debug-iphoneos/UITests-Runner.app/PlugIns/UITests.xctest/UITests” | xargs -s 262144 xcrun swift-demangle
Error: xargs: xcrun: Argument list too long
Command failed: nm -gU “/Users/vagrant/deploy/Debug-iphoneos/UITests-Runner.app/PlugIns/UITests.xctest/UITests” | xargs -s 262144 xcrun swift-demangle
[33;1mFlank exited with status code `1`: A general failure occurred. Possible causes include: a filename that does not exist or an HTTP/network error.[0m
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank shouldn't fail why searching .xctest for test names.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

21.01.1

**Additional context**
> Add any other context about the problem here.
Error occurs in `parseSwiftTests()` method. 
```
val cmd = if (isMacOS) {
    "nm -gU ${binary.quote()} | xargs -s $argMax xcrun swift-demangle"
} else {
    "export LD_LIBRARY_PATH=~/.flank; export PATH=~/.flank:\$PATH; nm -gU ${binary.quote()} | xargs -s $argMax swift-demangle"
}
```

### PR DESCRIPTION
**Pull request by Sloox**
Fixes #1538 

A small update to use a default option instead of failing straight out if the maxArgs is reached.

## Checklist
- [x] Integration tests updated

### CODE REVIEW

**Comment by Sloox** [comment]
@flank-it

File: test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt [hunk 1]
```diff
@@ -45,3 +45,10 @@ internal fun parseSwiftTests(binary: String): List<String> {
     }
     return results.distinct()
 }
+
+private fun String.determineXArgsCommand(argsMax: Int) = if (this.length > argsMax) {
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/ios/xctest/common/ParseSwiftTests.kt:49]:
```suggestion
private fun String.determineXArgsCommand(argsMax: Int) = if (length > argsMax) {
```

**Review by piotradamczyk5 — APPROVED** [review]

**Review by jan-gogo — APPROVED** [review]
