### PR TITLE
fix: Move shards json to result directory

### LINKED ISSUE #1475: Move shards.json to results directory
**Describe the bug**
> A clear and concise description of what the bug is.

Currently, flank always saves shards file in the current directory. This behavior can cause overriding this file when user run flank multiple times at the same time.

**Expected behavior**
> A clear and concise description of what you expected to happen. 

When we run tests we should save shards file to result directory. This behavior can cause overriding this file when user run flank multiple times at the same time.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1475 

1. Run flank with android or ios test
1. Wait until ```results-directory``` is created
1. Open the results directory and check ```*_shards.json``` exists
1. If   ```disable-results-upload``` not set, check shards file exists in gcloud bucket 
1. Flank shouldn't upload shards file to gcs if ```disable-results-upload``` set

## Checklist

- [X] Documented [(SDD in ticket comment)](https://github.com/Flank/flank/issues/1475#issuecomment-769227112)
- [x] Unit tests updated
- [X] Integration tests updated

### CODE REVIEW

**Comment by adamfilipow92** [comment]
@flank-it

**Review by Sloox — APPROVED** [review]

File: test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt [hunk 1]
```diff
@@ -151,5 +153,8 @@ val AndroidArgs.isSanityRobo
 val AndroidArgs.isGameLoop
     get() = if (type == null) false else (type == Type.GAMELOOP)
 
+val AndroidArgs.shardsFilePath
+    get() = Paths.get(localResultDir, resultsDir, ANDROID_SHARD_FILE).toAbsolutePath().toString()
```
Comment (piotradamczyk5) [inline test_runner/src/main/kotlin/ftl/args/AndroidArgs.kt:157]: if `localResultsDir` is different than default, we should not add file to `resultsDir`. We have similar logic in the whole app

**Review by piotradamczyk5 — APPROVED** [review]
